# -*- coding: utf-8 -*-
#!/usr/bin/env python3
# One-off: append NEW original English CEFR reading passages (10 questions each)
# to data/readingcompencefr.js, before the closing '];'. All content original.
import re

PATH = r"c:\gitrepo\udsp\data\readingcompencefr.js"

PASSAGES = [
  {"level":"A1","title":"My School Day","text":"I go to school every morning. My school is big. My favorite subject is math. I have lunch at twelve o'clock. In the afternoon, I have English class. My teacher is very kind. After school, I walk home with my friend. In the evening, I do my homework.","questions":[
    {"q":"When does the writer go to school?","options":["At night","Every morning","On weekends","At noon"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says the writer goes to school every morning."},
    {"q":"How is the school described?","options":["Small","Big","Old","New"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says the school is big."},
    {"q":"What is the writer's favorite subject?","options":["English","Math","Art","Music"],"correct":1,"hint":"Look at the third sentence.","explain":"The text says the favorite subject is math."},
    {"q":"When does the writer have lunch?","options":["At ten o'clock","At twelve o'clock","At two o'clock","In the evening"],"correct":1,"hint":"Look at the sentence about lunch.","explain":"The text says lunch is at twelve o'clock."},
    {"q":"What class does the writer have in the afternoon?","options":["Math","English","Science","Sport"],"correct":1,"hint":"Look at the sentence about the afternoon.","explain":"The text says the writer has English class in the afternoon."},
    {"q":"How is the teacher?","options":["Very strict","Very kind","Very tired","Very loud"],"correct":1,"hint":"Look at the sentence about the teacher.","explain":"The text says the teacher is very kind."},
    {"q":"Who does the writer walk home with?","options":["A brother","A friend","A teacher","No one"],"correct":1,"hint":"Look at the sentence about after school.","explain":"The text says the writer walks home with a friend."},
    {"q":"When does the writer do homework?","options":["In the morning","At lunch","In the afternoon","In the evening"],"correct":3,"hint":"Look at the last sentence.","explain":"The text says the writer does homework in the evening."},
    {"q":"How does the writer get home after school?","options":["By bus","By walking","By car","By bike"],"correct":1,"hint":"Look at the sentence about after school.","explain":"The text says the writer walks home."},
    {"q":"Does the writer like math?","options":["No","Yes, it is the favorite subject","The text does not say","Only a little"],"correct":1,"hint":"Look at the sentence about the favorite subject.","explain":"Math is the writer's favorite subject, so yes."},
  ]},
  {"level":"A1","title":"The Little Garden","text":"My grandmother has a small garden. In the garden, there are red roses and yellow flowers. She grows tomatoes and carrots. A little bird lives in the tree. Every morning, my grandmother waters the plants. In summer, we eat vegetables from the garden. I love the garden very much.","questions":[
    {"q":"Who has the garden?","options":["The writer","The grandmother","A friend","The neighbor"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says the writer's grandmother has the garden."},
    {"q":"How big is the garden?","options":["Very big","Small","Huge","Medium"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says the garden is small."},
    {"q":"What color are the roses?","options":["Red","Yellow","White","Pink"],"correct":0,"hint":"Look at the second sentence.","explain":"The text says there are red roses."},
    {"q":"What vegetables grow in the garden?","options":["Potatoes and beans","Tomatoes and carrots","Onions and peas","Corn and cabbage"],"correct":1,"hint":"Look at the third sentence.","explain":"The text says she grows tomatoes and carrots."},
    {"q":"What lives in the tree?","options":["A cat","A little bird","A squirrel","A butterfly"],"correct":1,"hint":"Look at the sentence about the tree.","explain":"The text says a little bird lives in the tree."},
    {"q":"When does the grandmother water the plants?","options":["Every evening","Every morning","Once a week","On Sundays"],"correct":1,"hint":"Look at the sentence about watering.","explain":"The text says she waters the plants every morning."},
    {"q":"When do they eat vegetables from the garden?","options":["In winter","In summer","In autumn","All year"],"correct":1,"hint":"Look at the sentence about eating vegetables.","explain":"The text says they eat vegetables in summer."},
    {"q":"What color are the other flowers?","options":["Yellow","Blue","Purple","Orange"],"correct":0,"hint":"Look at the second sentence.","explain":"The text says there are yellow flowers."},
    {"q":"How does the writer feel about the garden?","options":["Does not like it","Loves it very much","Is afraid of it","Never visits it"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says the writer loves the garden very much."},
    {"q":"Does the grandmother grow any vegetables?","options":["No, only flowers","Yes, tomatoes and carrots","Only fruit","The text does not say"],"correct":1,"hint":"Look at the third sentence.","explain":"She grows tomatoes and carrots."},
  ]},
  {"level":"A2","title":"A Trip to the Zoo","text":"Last Sunday, my family went to the zoo. We saw many animals. The lions were sleeping in the sun. My little sister loved the monkeys because they were funny. We watched the penguins swim in cold water. At lunchtime, we ate sandwiches near the elephants. Before we left, I bought a small toy giraffe. It was a wonderful day.","questions":[
    {"q":"When did the family go to the zoo?","options":["Last Saturday","Last Sunday","Last Monday","Yesterday"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says they went last Sunday."},
    {"q":"What were the lions doing?","options":["Eating","Sleeping in the sun","Running","Roaring"],"correct":1,"hint":"Look at the sentence about lions.","explain":"The text says the lions were sleeping in the sun."},
    {"q":"Which animals did the little sister love?","options":["The lions","The monkeys","The penguins","The elephants"],"correct":1,"hint":"Look at the sentence about the sister.","explain":"The text says she loved the monkeys."},
    {"q":"Why did the sister love those animals?","options":["They were big","They were funny","They were fast","They were loud"],"correct":1,"hint":"Look at the sentence about the sister.","explain":"The text says she loved the monkeys because they were funny."},
    {"q":"What were the penguins doing?","options":["Sleeping","Swimming in cold water","Eating fish","Walking on ice"],"correct":1,"hint":"Look at the sentence about penguins.","explain":"The text says they watched the penguins swim in cold water."},
    {"q":"Where did the family eat lunch?","options":["Near the elephants","In a restaurant","At home","Near the lions"],"correct":0,"hint":"Look at the sentence about lunchtime.","explain":"The text says they ate sandwiches near the elephants."},
    {"q":"What did they eat at lunchtime?","options":["Pizza","Sandwiches","Ice cream","Fruit"],"correct":1,"hint":"Look at the sentence about lunchtime.","explain":"The text says they ate sandwiches."},
    {"q":"What did the writer buy before leaving?","options":["A toy lion","A small toy giraffe","A book","A hat"],"correct":1,"hint":"Look at the sentence before the last.","explain":"The text says the writer bought a small toy giraffe."},
    {"q":"How did the writer describe the day?","options":["Boring","Wonderful","Tiring","Too short"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says it was a wonderful day."},
    {"q":"Who went to the zoo?","options":["The writer alone","The writer's family","A school class","Some friends"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says the writer's family went to the zoo."},
  ]},
  {"level":"A2","title":"Learning to Cook","text":"My brother is learning to cook. Last week, he made pasta for the whole family. First, he boiled water in a big pot. Then he added the pasta and some salt. While the pasta cooked, he prepared a tomato sauce. He was a little nervous, but the food tasted great. Now he wants to cook dinner every weekend.","questions":[
    {"q":"Who is learning to cook?","options":["The writer","The writer's brother","The writer's mother","A friend"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says the writer's brother is learning to cook."},
    {"q":"What did the brother make last week?","options":["Pizza","Pasta","Soup","Cake"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says he made pasta."},
    {"q":"Who did he cook for?","options":["Just himself","The whole family","His friends","His teacher"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says he made pasta for the whole family."},
    {"q":"What did he do first?","options":["Added the pasta","Boiled water in a big pot","Made the sauce","Set the table"],"correct":1,"hint":"Look at the sentence starting with 'First'.","explain":"The text says first he boiled water in a big pot."},
    {"q":"What did he add to the water?","options":["Only pasta","The pasta and some salt","Sugar","Oil"],"correct":1,"hint":"Look at the sentence starting with 'Then'.","explain":"The text says he added the pasta and some salt."},
    {"q":"What sauce did he prepare?","options":["A cheese sauce","A tomato sauce","A cream sauce","No sauce"],"correct":1,"hint":"Look at the sentence about the sauce.","explain":"The text says he prepared a tomato sauce."},
    {"q":"How did the brother feel while cooking?","options":["Very calm","A little nervous","Angry","Bored"],"correct":1,"hint":"Look at the sentence about his feelings.","explain":"The text says he was a little nervous."},
    {"q":"How did the food taste?","options":["Great","Terrible","Too salty","Cold"],"correct":0,"hint":"Look at the sentence about the food.","explain":"The text says the food tasted great."},
    {"q":"What does the brother want to do now?","options":["Stop cooking","Cook dinner every weekend","Open a restaurant","Cook only pasta"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says he wants to cook dinner every weekend."},
    {"q":"When did the brother make the pasta?","options":["Yesterday","Last week","Last month","Today"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says he made pasta last week."},
  ]},
  {"level":"B1","title":"The Benefits of Reading","text":"Reading regularly offers many benefits for people of all ages. It improves vocabulary and helps readers express their ideas more clearly. Studies suggest that reading fiction can increase empathy, because readers imagine the lives and feelings of different characters. Reading before bed can also help people relax and sleep better than looking at a screen. Although some people say they have no time to read, experts recommend starting with just ten minutes a day. Over time, this small habit can make a big difference.","questions":[
    {"q":"Who can benefit from reading regularly, according to the text?","options":["Only children","People of all ages","Only students","Only writers"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says reading offers benefits for people of all ages."},
    {"q":"What language skill does reading improve?","options":["Handwriting","Vocabulary","Pronunciation only","Spelling only"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says reading improves vocabulary."},
    {"q":"What can reading fiction increase, according to studies?","options":["Empathy","Speed","Wealth","Height"],"correct":0,"hint":"Look at the sentence about fiction.","explain":"The text says reading fiction can increase empathy."},
    {"q":"Why does fiction increase empathy, according to the text?","options":["It is difficult","Readers imagine the lives and feelings of characters","It is short","It has pictures"],"correct":1,"hint":"Look at the sentence about fiction.","explain":"The text says readers imagine the lives and feelings of different characters."},
    {"q":"What can reading before bed help people do?","options":["Relax and sleep better","Stay awake longer","Eat less","Exercise more"],"correct":0,"hint":"Look at the sentence about bed.","explain":"The text says reading before bed can help people relax and sleep better."},
    {"q":"What is reading before bed compared to in the text?","options":["Listening to music","Looking at a screen","Drinking tea","Going for a walk"],"correct":1,"hint":"Look at the sentence about bed.","explain":"The text compares it to looking at a screen."},
    {"q":"What reason do some people give for not reading?","options":["They dislike books","They have no time","They cannot read","Books are expensive"],"correct":1,"hint":"Look at the sentence starting with 'Although'.","explain":"The text says some people say they have no time to read."},
    {"q":"How much reading do experts recommend starting with?","options":["One hour a day","Ten minutes a day","Two books a week","Thirty minutes a day"],"correct":1,"hint":"Look at the sentence about experts.","explain":"The text says experts recommend starting with just ten minutes a day."},
    {"q":"What can the small habit of reading do over time?","options":["Make a big difference","Waste time","Cost a lot of money","Become boring"],"correct":0,"hint":"Look at the last sentence.","explain":"The text says over time this small habit can make a big difference."},
    {"q":"According to the text, does reading help people express ideas?","options":["No","Yes, more clearly","Only in writing","Only for experts"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says it helps readers express their ideas more clearly."},
  ]},
  {"level":"B1","title":"Volunteering in the Community","text":"Many people choose to spend some of their free time volunteering in their local community. Volunteers might help at a food bank, teach children to read, or care for animals at a shelter. Besides helping others, volunteering can also benefit the volunteers themselves. It allows them to learn new skills, meet new people, and feel more connected to their community. Some studies even suggest that people who volunteer regularly report feeling happier and less stressed. For many, the sense of purpose it brings is the greatest reward.","questions":[
    {"q":"What do many people choose to do with some free time, according to the text?","options":["Volunteer in their community","Watch television","Travel abroad","Sleep more"],"correct":0,"hint":"Look at the first sentence.","explain":"The text says many people volunteer in their local community."},
    {"q":"Which is an example of volunteering given in the text?","options":["Helping at a food bank","Running a company","Selling products","Driving a taxi"],"correct":0,"hint":"Look at the second sentence.","explain":"The text mentions helping at a food bank."},
    {"q":"Besides helping others, who else can volunteering benefit?","options":["No one","The volunteers themselves","Only companies","Only children"],"correct":1,"hint":"Look at the sentence about benefits.","explain":"The text says volunteering can also benefit the volunteers themselves."},
    {"q":"What does volunteering allow people to learn?","options":["New skills","New languages only","Nothing new","Only cooking"],"correct":0,"hint":"Look at the sentence about skills.","explain":"The text says it allows them to learn new skills."},
    {"q":"How do regular volunteers report feeling, according to studies?","options":["Happier and less stressed","Tired and bored","Angry","Lonely"],"correct":0,"hint":"Look at the sentence about studies.","explain":"The text says they report feeling happier and less stressed."},
    {"q":"What might volunteers do at a shelter?","options":["Care for animals","Cook meals","Build houses","Teach math"],"correct":0,"hint":"Look at the second sentence.","explain":"The text mentions caring for animals at a shelter."},
    {"q":"What social benefit does volunteering bring, according to the text?","options":["Meeting new people","Earning money","Getting famous","Winning prizes"],"correct":0,"hint":"Look at the sentence about benefits.","explain":"The text says volunteers meet new people."},
    {"q":"For many volunteers, what is the greatest reward?","options":["Money","A sense of purpose","Free food","Fame"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says the sense of purpose is the greatest reward."},
    {"q":"What might volunteers teach children to do?","options":["To read","To swim","To drive","To cook"],"correct":0,"hint":"Look at the second sentence.","explain":"The text mentions teaching children to read."},
    {"q":"Does volunteering help people feel connected to their community?","options":["No","Yes","Only sometimes for money","The text does not say"],"correct":1,"hint":"Look at the sentence about connection.","explain":"The text says it helps them feel more connected to their community."},
  ]},
  {"level":"B2","title":"The Importance of Sleep","text":"Sleep is often the first thing people sacrifice when life becomes busy, yet scientists increasingly warn that this is a serious mistake. During sleep, the brain consolidates memories, repairs cells, and clears out waste products that build up during the day. Chronic sleep deprivation has been linked to a range of problems, including weakened immunity, difficulty concentrating, and a higher risk of certain diseases. Despite this, many adults regularly get less than the recommended seven to nine hours. Experts suggest keeping a consistent sleep schedule and avoiding screens before bed as practical ways to improve sleep quality.","questions":[
    {"q":"What do people often sacrifice when life becomes busy?","options":["Food","Sleep","Exercise","Work"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says sleep is often the first thing people sacrifice."},
    {"q":"How do scientists view sacrificing sleep?","options":["As a good idea","As a serious mistake","As unimportant","As necessary"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says scientists warn it is a serious mistake."},
    {"q":"What does the brain do during sleep, according to the text?","options":["Nothing","Consolidates memories and repairs cells","Uses more energy","Grows larger"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says the brain consolidates memories, repairs cells, and clears waste."},
    {"q":"What has chronic sleep deprivation been linked to?","options":["Better health","Weakened immunity and poor concentration","More energy","Faster memory"],"correct":1,"hint":"Look at the sentence about deprivation.","explain":"The text links it to weakened immunity, difficulty concentrating, and disease risk."},
    {"q":"How many hours of sleep are recommended, according to the text?","options":["Four to five","Seven to nine","Ten to twelve","Three to four"],"correct":1,"hint":"Look at the sentence about hours.","explain":"The text mentions the recommended seven to nine hours."},
    {"q":"Do many adults get enough sleep, according to the text?","options":["Yes, always","No, many get less than recommended","Only children do not","The text does not say"],"correct":1,"hint":"Look at the sentence starting with 'Despite this'.","explain":"The text says many adults regularly get less than the recommended amount."},
    {"q":"What do experts suggest for better sleep?","options":["Drinking coffee at night","Keeping a consistent sleep schedule","Sleeping in the day","Exercising at midnight"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says experts suggest keeping a consistent sleep schedule."},
    {"q":"What should people avoid before bed, according to experts?","options":["Reading","Screens","Warm milk","Quiet rooms"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says experts suggest avoiding screens before bed."},
    {"q":"What builds up in the brain during the day?","options":["Memories","Waste products","Water","Energy"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says the brain clears out waste products that build up during the day."},
    {"q":"What is the main message of the text?","options":["Sleep is a waste of time","Sleep is very important for health","People sleep too much","Sleep has no effect"],"correct":1,"hint":"Consider the whole passage.","explain":"The text argues that sleep is important and should not be sacrificed."},
  ]},
  {"level":"B2","title":"The Growth of Online Shopping","text":"Over the last two decades, online shopping has transformed the way people buy goods. Consumers can now compare prices, read reviews, and order products from around the world without leaving their homes. This convenience has come at a cost, however, as many traditional shops have struggled to compete and some have closed entirely. Online shopping has also raised concerns about the environmental impact of packaging and rapid delivery. Despite these challenges, most analysts expect online retail to keep growing, especially as technology makes the experience faster and more personalized.","questions":[
    {"q":"What has online shopping transformed over the last two decades?","options":["The way people travel","The way people buy goods","The way people cook","The way people sleep"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says online shopping has transformed the way people buy goods."},
    {"q":"What can consumers now do, according to the text?","options":["Compare prices and read reviews","Only buy local products","Avoid all shops","Pay only with cash"],"correct":0,"hint":"Look at the second sentence.","explain":"The text says consumers can compare prices, read reviews, and order from around the world."},
    {"q":"What negative effect has this convenience had on traditional shops?","options":["They became more popular","Many have struggled and some closed","They lowered prices","They moved online easily"],"correct":1,"hint":"Look at the sentence starting with 'This convenience'.","explain":"The text says many traditional shops have struggled and some have closed."},
    {"q":"What environmental concerns has online shopping raised?","options":["Packaging and rapid delivery","Water use","Air travel","Farming"],"correct":0,"hint":"Look at the sentence about the environment.","explain":"The text mentions concerns about packaging and rapid delivery."},
    {"q":"What do most analysts expect for online retail?","options":["It will disappear","It will keep growing","It will stay the same","It will become illegal"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says most analysts expect online retail to keep growing."},
    {"q":"Why do analysts expect this trend, according to the text?","options":["Because shops are closing","Because technology makes it faster and more personalized","Because it is cheaper for shops","Because people dislike stores"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says technology makes the experience faster and more personalized."},
    {"q":"Where can consumers order products from now?","options":["Only their own city","From around the world","Only from one country","Only from local shops"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says consumers can order products from around the world."},
    {"q":"Do consumers need to leave home to shop online?","options":["Yes","No","Only for large items","Only on weekends"],"correct":1,"hint":"Look at the second sentence.","explain":"The text says they can shop without leaving their homes."},
    {"q":"How does the text describe the effect of online shopping overall?","options":["Entirely positive","Both convenient and challenging","Entirely negative","Unimportant"],"correct":1,"hint":"Consider the whole passage.","explain":"The text presents both convenience and costs such as closed shops and environmental concerns."},
    {"q":"How long has online shopping been transforming buying, according to the text?","options":["Over the last two decades","For one year","For fifty years","For a few months"],"correct":0,"hint":"Look at the first sentence.","explain":"The text says over the last two decades."},
  ]},
  {"level":"C1","title":"The Psychology of Habits","text":"Habits are the automatic behaviors that shape a surprising proportion of our daily lives, from the route we take to work to the way we respond to stress. Psychologists describe habits as following a loop consisting of a cue, a routine, and a reward. Once this loop is firmly established, the brain stops actively deciding and simply follows the pattern, which conserves mental energy but can also entrench undesirable behaviors. Research suggests that the most effective way to change a habit is not to eliminate it outright but to keep the same cue and reward while replacing the routine. Understanding this mechanism gives individuals a practical framework for building healthier habits and gradually dismantling harmful ones.","questions":[
    {"q":"What are habits, according to the text?","options":["Rare events","Automatic behaviors that shape much of daily life","Conscious decisions","Difficult skills"],"correct":1,"hint":"Look at the first sentence.","explain":"The text describes habits as automatic behaviors that shape a surprising proportion of daily life."},
    {"q":"What three parts make up the habit loop?","options":["A cue, a routine, and a reward","A start, a middle, and an end","A cause, an effect, and a result","A plan, an action, and a review"],"correct":0,"hint":"Look at the second sentence.","explain":"The text says the loop consists of a cue, a routine, and a reward."},
    {"q":"What happens once the loop is firmly established?","options":["The brain decides carefully each time","The brain stops actively deciding and follows the pattern","The habit disappears","The reward changes"],"correct":1,"hint":"Look at the third sentence.","explain":"The text says the brain stops actively deciding and simply follows the pattern."},
    {"q":"What is one benefit of following an established loop?","options":["It conserves mental energy","It costs more energy","It slows the brain","It removes rewards"],"correct":0,"hint":"Look at the third sentence.","explain":"The text says following the pattern conserves mental energy."},
    {"q":"What is a downside of firmly established loops?","options":["They use too much energy","They can entrench undesirable behaviors","They require constant thought","They are easy to change"],"correct":1,"hint":"Look at the third sentence.","explain":"The text says the loop can entrench undesirable behaviors."},
    {"q":"What is the most effective way to change a habit, according to research?","options":["Eliminate it outright","Keep the same cue and reward while replacing the routine","Change the reward only","Ignore the cue"],"correct":1,"hint":"Look at the sentence about research.","explain":"The text says to keep the same cue and reward while replacing the routine."},
    {"q":"What does understanding this mechanism give individuals?","options":["A practical framework for building healthier habits","A cure for all diseases","A way to avoid all habits","More free time only"],"correct":0,"hint":"Look at the last sentence.","explain":"The text says it gives a practical framework for building healthier habits."},
    {"q":"Which everyday example of a habit does the text mention?","options":["The route we take to work","The food we cook","The books we read","The clothes we buy"],"correct":0,"hint":"Look at the first sentence.","explain":"The text mentions the route we take to work."},
    {"q":"According to the text, should you try to eliminate a habit outright?","options":["Yes, always","No, it is better to replace the routine","Only for good habits","The text does not say"],"correct":1,"hint":"Look at the sentence about research.","explain":"The text says the most effective way is not to eliminate it but to replace the routine."},
    {"q":"What does the habit loop allow the brain to avoid?","options":["Active decision-making each time","Sleeping","Eating","Learning"],"correct":0,"hint":"Look at the third sentence.","explain":"The text says the brain stops actively deciding."},
  ]},
  {"level":"C1","title":"The Challenges of Urbanization","text":"As more of the world's population moves from rural areas into cities, urban planners face mounting challenges in accommodating this rapid growth. Overcrowding can strain public services, drive up housing costs, and increase pollution, particularly in cities that expand faster than their infrastructure. At the same time, well-managed urbanization can bring significant benefits, concentrating economic opportunity, education, and healthcare in ways that improve living standards. The key, many experts argue, lies in thoughtful planning that prioritizes affordable housing, efficient public transport, and green spaces. Cities that fail to plan for growth often find the problems far harder and more expensive to solve later.","questions":[
    {"q":"Where is the world's population increasingly moving, according to the text?","options":["From cities to rural areas","From rural areas into cities","To other countries","To the coast"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says people move from rural areas into cities."},
    {"q":"Who faces mounting challenges from this growth?","options":["Farmers","Urban planners","Tourists","Teachers"],"correct":1,"hint":"Look at the first sentence.","explain":"The text says urban planners face mounting challenges."},
    {"q":"What can overcrowding do, according to the text?","options":["Strain public services and raise housing costs","Lower pollution","Reduce housing costs","Improve infrastructure"],"correct":0,"hint":"Look at the second sentence.","explain":"The text says overcrowding can strain services, drive up housing costs, and increase pollution."},
    {"q":"When is pollution especially a problem?","options":["When cities expand faster than their infrastructure","When cities are small","When people leave cities","When housing is cheap"],"correct":0,"hint":"Look at the second sentence.","explain":"The text says particularly in cities that expand faster than their infrastructure."},
    {"q":"What benefit can well-managed urbanization bring?","options":["Concentrating economic opportunity and services","More rural farming","Fewer people","Lower education levels"],"correct":0,"hint":"Look at the third sentence.","explain":"The text says it can concentrate economic opportunity, education, and healthcare."},
    {"q":"What do experts say the key to good urbanization is?","options":["Thoughtful planning","Stopping all growth","Building only offices","Removing green spaces"],"correct":0,"hint":"Look at the fourth sentence.","explain":"The text says the key lies in thoughtful planning."},
    {"q":"What should thoughtful planning prioritize, according to the text?","options":["Affordable housing, public transport, and green spaces","Only skyscrapers","Only roads","Only shopping centers"],"correct":0,"hint":"Look at the fourth sentence.","explain":"The text lists affordable housing, efficient public transport, and green spaces."},
    {"q":"What happens to cities that fail to plan for growth?","options":["They solve problems easily","They find problems harder and more expensive to solve later","They stop growing","They have no problems"],"correct":1,"hint":"Look at the last sentence.","explain":"The text says such cities find the problems far harder and more expensive to solve later."},
    {"q":"Does the text present urbanization as only negative?","options":["Yes","No, it can bring significant benefits too","It says nothing about benefits","Only for planners"],"correct":1,"hint":"Look at the third sentence.","explain":"The text says well-managed urbanization can bring significant benefits."},
    {"q":"What can concentrating healthcare and education improve?","options":["Living standards","Pollution","Traffic only","Farming"],"correct":0,"hint":"Look at the third sentence.","explain":"The text says it improves living standards."},
  ]},
  {"level":"C2","title":"The Problem of Free Will","text":"Few questions have preoccupied philosophers as persistently as whether human beings genuinely possess free will. Determinists argue that every event, including every human decision, is the inevitable consequence of prior causes governed by the laws of nature, leaving no room for genuine choice. Libertarians, by contrast, maintain that individuals can act as true originators of their actions, exercising a freedom that cannot be reduced to mere physical processes. A third position, compatibilism, attempts to reconcile the two by redefining freedom not as the absence of causation but as the capacity to act according to one's own motives without external coercion. Far from a purely academic dispute, the debate carries profound implications for how societies assign moral responsibility and administer justice.","questions":[
    {"q":"What central question does the text address?","options":["Whether humans possess free will","Whether the universe is infinite","Whether animals think","Whether time is real"],"correct":0,"hint":"Look at the first sentence.","explain":"The text asks whether human beings genuinely possess free will."},
    {"q":"What do determinists argue?","options":["Every event is the inevitable consequence of prior causes","Humans are entirely free","Nothing can be predicted","Choices have no causes"],"correct":0,"hint":"Look at the sentence about determinists.","explain":"The text says determinists argue every event is the inevitable consequence of prior causes."},
    {"q":"According to determinists, is there room for genuine choice?","options":["Yes, complete freedom","No room for genuine choice","Only for some people","Only in emergencies"],"correct":1,"hint":"Look at the sentence about determinists.","explain":"The text says determinism leaves no room for genuine choice."},
    {"q":"What do libertarians maintain?","options":["Individuals can be true originators of their actions","All actions are predetermined","Freedom is an illusion","Only laws of nature matter"],"correct":0,"hint":"Look at the sentence about libertarians.","explain":"The text says libertarians maintain individuals can act as true originators of their actions."},
    {"q":"What is the third position called?","options":["Determinism","Compatibilism","Libertarianism","Skepticism"],"correct":1,"hint":"Look at the sentence about the third position.","explain":"The text names the third position compatibilism."},
    {"q":"How does compatibilism redefine freedom?","options":["As the absence of all causation","As the capacity to act according to one's own motives without coercion","As random behavior","As following the laws of nature exactly"],"correct":1,"hint":"Look at the sentence about compatibilism.","explain":"The text says compatibilism defines freedom as acting on one's own motives without external coercion."},
    {"q":"What does compatibilism try to do?","options":["Reject both other views","Reconcile determinism and libertarianism","Prove free will is fake","End the debate forever"],"correct":1,"hint":"Look at the sentence about compatibilism.","explain":"The text says compatibilism attempts to reconcile the two views."},
    {"q":"Why is the debate more than academic, according to the text?","options":["It affects how societies assign moral responsibility and justice","It has no practical effect","It is only about language","It concerns only scientists"],"correct":0,"hint":"Look at the last sentence.","explain":"The text says the debate carries implications for moral responsibility and justice."},
    {"q":"According to libertarians, can freedom be reduced to physical processes?","options":["Yes","No, it cannot be reduced to mere physical processes","Only partly","The text does not say"],"correct":1,"hint":"Look at the sentence about libertarians.","explain":"The text says libertarians see a freedom that cannot be reduced to mere physical processes."},
    {"q":"What governs prior causes, according to determinists?","options":["The laws of nature","Human wishes","Random chance","Government rules"],"correct":0,"hint":"Look at the sentence about determinists.","explain":"The text says prior causes are governed by the laws of nature."},
  ]},
  {"level":"C2","title":"The Paradoxes of Globalization","text":"Globalization, the increasing interconnection of economies and cultures across national borders, has generated both unprecedented prosperity and persistent controversy. Proponents credit it with lifting hundreds of millions out of poverty by integrating developing nations into global markets and accelerating the exchange of ideas and technology. Critics counter that its benefits have been distributed unevenly, enriching some regions while hollowing out industries and communities in others, and that it has eroded local cultures in favor of a homogenized global consumerism. Complicating matters further, the very interconnectedness that fuels growth also transmits crises rapidly, as a financial shock or pandemic in one region can cascade across the entire system. Navigating these tensions remains one of the defining challenges of the contemporary era.","questions":[
    {"q":"How does the text define globalization?","options":["The increasing interconnection of economies and cultures across borders","The closing of national borders","The decline of technology","The end of trade"],"correct":0,"hint":"Look at the first sentence.","explain":"The text defines globalization as the increasing interconnection of economies and cultures across national borders."},
    {"q":"What do proponents credit globalization with?","options":["Lifting hundreds of millions out of poverty","Causing all wars","Ending all trade","Slowing technology"],"correct":0,"hint":"Look at the sentence about proponents.","explain":"The text says proponents credit it with lifting hundreds of millions out of poverty."},
    {"q":"How do proponents say poverty was reduced?","options":["By integrating developing nations into global markets","By closing markets","By stopping technology","By raising borders"],"correct":0,"hint":"Look at the sentence about proponents.","explain":"The text says it integrated developing nations into global markets."},
    {"q":"What do critics say about the benefits of globalization?","options":["They are distributed unevenly","They are shared equally","They do not exist","They only help the poor"],"correct":0,"hint":"Look at the sentence about critics.","explain":"The text says critics argue the benefits have been distributed unevenly."},
    {"q":"What cultural concern do critics raise?","options":["It has eroded local cultures in favor of global consumerism","It has strengthened all local cultures","It has ended all culture","It has no cultural effect"],"correct":0,"hint":"Look at the sentence about critics.","explain":"The text says critics argue it has eroded local cultures in favor of homogenized global consumerism."},
    {"q":"What negative effect does interconnectedness have, according to the text?","options":["It transmits crises rapidly","It stops all growth","It isolates regions","It slows communication"],"correct":0,"hint":"Look at the sentence about interconnectedness.","explain":"The text says interconnectedness transmits crises rapidly."},
    {"q":"What example of a fast-spreading crisis does the text give?","options":["A financial shock or pandemic","A local festival","A new invention","A sports event"],"correct":0,"hint":"Look at the sentence about crises.","explain":"The text mentions a financial shock or pandemic in one region cascading across the system."},
    {"q":"How does the text describe navigating these tensions?","options":["One of the defining challenges of the contemporary era","A simple task","An impossible goal","An unimportant issue"],"correct":0,"hint":"Look at the last sentence.","explain":"The text says navigating these tensions remains a defining challenge of the era."},
    {"q":"Does the text present globalization as entirely good or bad?","options":["Entirely good","Entirely bad","Both beneficial and controversial","Neither"],"correct":2,"hint":"Look at the first sentence.","explain":"The text says globalization has generated both prosperity and controversy."},
    {"q":"What did globalization accelerate, according to proponents?","options":["The exchange of ideas and technology","The closing of borders","The decline of trade","The loss of jobs everywhere"],"correct":0,"hint":"Look at the sentence about proponents.","explain":"The text says it accelerated the exchange of ideas and technology."},
  ]},
]


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def fmt_q(q):
    opts = ", ".join('"%s"' % esc(o) for o in q["options"])
    return ('      { q: "%s", options: [%s], correct: %d, hint: "%s", explain: "%s" },'
            % (esc(q["q"]), opts, q["correct"], esc(q["hint"]), esc(q["explain"])))


def fmt_p(p):
    lines = ["  {", '    level: "%s",' % p["level"], '    title: "%s",' % esc(p["title"]),
             '    text:', '      "%s",' % esc(p["text"]), "    questions: ["]
    for q in p["questions"]:
        if len(q["options"]) != 4:
            raise SystemExit("bad options count in: " + q["q"])
        lines.append(fmt_q(q))
    lines += ["    ],", "  },"]
    return "\n".join(lines)


def main():
    text = open(PATH, encoding="utf-8").read()
    marker = "\n];"
    pos = text.rfind(marker)
    if pos < 0:
        raise SystemExit("array terminator not found")
    block = "\n" + "\n".join(fmt_p(p) for p in PASSAGES)
    text = text[:pos] + block + text[pos:]
    open(PATH, "w", encoding="utf-8", newline="\n").write(text)
    print("appended %d new EN passages (%d questions)" % (len(PASSAGES), sum(len(p["questions"]) for p in PASSAGES)))


if __name__ == "__main__":
    main()
