# -*- coding: utf-8 -*-
"""Authored replacements for inflected headwords.

    "<file>|<old word>": (new_word, new_pos, new_definition, new_example)

An empty new_example means "keep the existing example sentence".
Definitions follow the German-file house style: lowercase English gloss,
" - " separator, Turkish gloss, both ending in a period.
"""

CONTENT = {
    # ===== wordsa1gode.js
    "wordsa1gode.js|Knurren": ("knurren", "verb", "to growl; to rumble. - hırlamak; guruldamak.", ""),
    "wordsa1gode.js|Messen": ("messen", "verb", "to measure. - ölçmek.", ""),
    "wordsa1gode.js|Misstrauen": ("Misstrauen", "noun", "mistrust, distrust. - güvensizlik, kuşku.", ""),
    "wordsa1gode.js|Nachkommen": ("Nachkomme", "noun", "descendant, offspring. - torun, soydan gelen.",
                                  "Er ist ein direkter Nachkomme des Dichters. - O, şairin doğrudan bir torunudur."),
    "wordsa1gode.js|Nachäffen": ("nachäffen", "verb", "to ape, to mimic mockingly. - alaycı biçimde taklit etmek.",
                                 "Er versucht ständig, seinen großen Bruder nachzuäffen. - Sürekli ağabeyini taklit etmeye çalışıyor."),

    # ===== wordsa2gode.js
    "wordsa2gode.js|Abfragen": ("abfragen", "verb", "to query; to test someone orally. - sorgulamak; sözlü olarak yoklamak.", ""),
    "wordsa2gode.js|Abheften": ("abheften", "verb", "to file away (papers). - (evrakı) dosyalamak.",
                                "Bitte die Rechnungen sorgfältig abheften! - Lütfen faturaları özenle dosyalayın!"),
    "wordsa2gode.js|Abkommen": ("Abkommen", "noun", "agreement, treaty. - anlaşma, antlaşma.", ""),
    "wordsa2gode.js|Abschneiden": ("abschneiden", "verb", "to cut off; to fare well or badly. - kesmek; (iyi ya da kötü) sonuç almak.", ""),
    "wordsa2gode.js|Abschwören": ("abschwören", "verb", "to renounce, to abjure. - yeminle vazgeçmek, tövbe etmek.",
                                  "Er wollte seinem alten Glauben abschwören. - Eski inancından yeminle vazgeçmek istedi."),
    "wordsa2gode.js|Absenden": ("absenden", "verb", "to send off, to dispatch. - göndermek, yollamak.", ""),
    "wordsa2gode.js|Abstimmen": ("abstimmen", "verb", "to vote; to coordinate. - oy vermek; uyumlu hâle getirmek.",
                                 "Wir werden morgen über den Vorschlag abstimmen. - Yarın öneri hakkında oy vereceğiz."),
    "wordsa2gode.js|Adressieren": ("adressieren", "verb", "to address (a letter). - (mektup) adreslemek.", ""),
    "wordsa2gode.js|Allüren": ("Allüre", "noun", "airs, affected manner. - caka, havalı tavır.",
                               "Diese Allüre passt nicht zu ihm. - Bu tavır ona yakışmıyor."),
    "wordsa2gode.js|Anheften": ("anheften", "verb", "to attach, to pin on. - iliştirmek, iğnelemek.",
                                "Sie wollte sich die Brosche ans Kleid anheften. - Broşu elbisesine iliştirmek istedi."),
    "wordsa2gode.js|Anschreiben": ("anschreiben", "verb", "to write to someone; to put on the tab. - birine yazmak; veresiye yazmak.", ""),
    "wordsa2gode.js|Ansiedeln": ("ansiedeln", "verb", "to settle, to establish oneself somewhere. - yerleşmek, yerleştirmek.", ""),
    "wordsa2gode.js|Durchbrennen": ("durchbrennen", "verb", "to blow (a fuse), to burn through; to run away. - (sigorta) atmak, yanmak; kaçmak.",
                                    "Die Sicherung ist durchgebrannt. - Sigorta attı."),
    "wordsa2gode.js|Schlafengehen": ("Schlafengehen", "noun", "going to bed, bedtime. - yatma, uyumaya gitme.", ""),

    # ===== wordsb1gode.js
    "wordsb1gode.js|Aufsehen": ("Aufsehen", "noun", "stir, sensation, commotion. - sansasyon, dikkat çekme, gürültü.", ""),
    "wordsb1gode.js|Aufstellen": ("aufstellen", "verb", "to set up, to put up; to nominate. - kurmak, dikmek; aday göstermek.", ""),
    "wordsb1gode.js|Auseinandergehen": ("auseinandergehen", "verb", "to part, to break up; to diverge. - ayrılmak, dağılmak; farklılaşmak.", ""),
    "wordsb1gode.js|Aushalten": ("aushalten", "verb", "to endure, to bear. - dayanmak, katlanmak.", ""),
    "wordsb1gode.js|Aussetzen": ("aussetzen", "verb", "to expose to; to suspend; to abandon. - maruz bırakmak; askıya almak; terk etmek.", ""),
    "wordsb1gode.js|Bauchschmerzen": ("Bauchschmerz", "noun", "stomach ache, belly ache. - karın ağrısı.",
                                      "Der Bauchschmerz ließ langsam nach. - Karın ağrısı yavaş yavaş geçti."),
    "wordsb1gode.js|Bedenken": ("Bedenken", "noun", "misgivings, reservations, concerns. - çekince, kaygı, endişe.", ""),
    "wordsb1gode.js|Beiwohnen": ("beiwohnen", "verb", "to attend, to be present at. - hazır bulunmak, katılmak.", ""),
    "wordsb1gode.js|Bellen": ("bellen", "verb", "to bark. - havlamak.", ""),
    "wordsb1gode.js|Bergsteigen": ("Bergsteigen", "noun", "mountaineering, mountain climbing. - dağcılık, dağa tırmanma.", ""),

    # ===== wordsb2gode.js
    "wordsb2gode.js|Beugen": ("beugen", "verb", "to bend; to inflect (grammar). - eğmek, bükmek; (dil bilgisi) çekimlemek.", ""),
    "wordsb2gode.js|Chancen": ("Chance", "noun", "chance, opportunity. - şans, fırsat.",
                               "Das ist deine letzte Chance. - Bu senin son şansın."),
    "wordsb2gode.js|Rütteln": ("rütteln", "verb", "to shake, to jolt. - sarsmak, silkelemek.", ""),
    "wordsb2gode.js|Scheren": ("scheren", "verb", "to shear, to clip. - kırkmak, kesmek.",
                               "Im Frühjahr scheren die Bauern ihre Schafe. - İlkbaharda çiftçiler koyunlarını kırkar."),
    "wordsb2gode.js|Schleifen": ("schleifen", "verb", "to grind, to sand; to drag. - bilemek, zımparalamak; sürüklemek.",
                                 "Er musste das Messer erst schleifen. - Önce bıçağı bilemesi gerekti."),
    "wordsb2gode.js|Stichpunkte": ("Stichpunkt", "noun", "bullet point, key point. - madde başı, ana nokta.",
                                   "Notieren Sie bitte jeden Stichpunkt einzeln. - Lütfen her ana noktayı ayrı ayrı not edin."),
    "wordsb2gode.js|Vergolden": ("vergolden", "verb", "to gild, to cover with gold. - yaldızlamak, altın kaplamak.", ""),
    "wordsb2gode.js|Verschrotten": ("verschrotten", "verb", "to scrap, to junk. - hurdaya çıkarmak.", ""),
    "wordsb2gode.js|Vorgehen": ("Vorgehen", "noun", "procedure, course of action. - yöntem, izlenen yol.", ""),
    "wordsb2gode.js|abgearbeitet": ("abgearbeitet", "adjective", "worn out from hard work. - çok çalışmaktan yıpranmış.", ""),
    "wordsb2gode.js|abgedroschen": ("abdreschen", "verb", "to thresh (grain) completely. - (tahılı) tümüyle harmanlamak.",
                                    "Die Bauern haben das Korn längst abgedroschen. - Çiftçiler ekini çoktan harmanladı."),
    "wordsb2gode.js|abgegriffen": ("abgreifen", "verb", "to tap or pick off (a signal); to wear by handling. - (sinyali) almak; elle yıpratmak.", ""),
    "wordsb2gode.js|abgehackt": ("abgehackt", "adjective", "chopped off; clipped, staccato. - koparılmış; kesik kesik.", ""),
    "wordsb2gode.js|abgehärtet": ("abgehärtet", "adjective", "hardened, toughened, inured. - sertleşmiş, dayanıklı hâle gelmiş.", ""),
    "wordsb2gode.js|abgekapselt": ("abgekapselt", "adjective", "encapsulated, isolated, cut off. - kapsüllenmiş, dış dünyadan yalıtılmış.",
                                   "Er lebt völlig abgekapselt von der Außenwelt. - Dış dünyadan tamamen kopuk yaşıyor."),
    "wordsb2gode.js|abgeklungen": ("abklingen", "verb", "to subside, to fade away. - hafiflemek, yatışmak.", ""),
    "wordsb2gode.js|abgeklärt": ("abgeklärt", "adjective", "serene, level-headed, mellowed by experience. - olgun, sakin, dünyayı görmüş.", ""),
    "wordsb2gode.js|abgelegen": ("abliegen", "verb", "to lie at a distance, to be situated away. - uzakta bulunmak.", ""),
    "wordsb2gode.js|abgeleitet": ("abgeleitet", "adjective", "derived. - türetilmiş.", ""),
    "wordsb2gode.js|abgemacht": ("abgemacht", "adjective", "agreed, settled. - anlaştık, tamamdır.", ""),
    "wordsb2gode.js|abgemagert": ("abgemagert", "adjective", "emaciated, gaunt. - bir deri bir kemik kalmış, zayıflamış.", ""),
    "wordsb2gode.js|abgenutzt": ("abgenutzt", "adjective", "worn out, well-worn. - eskimiş, yıpranmış.", ""),
    "wordsb2gode.js|abgepackt": ("abgepackt", "adjective", "prepackaged. - önceden paketlenmiş.", ""),
    "wordsb2gode.js|abgerundet": ("abgerundet", "adjective", "rounded; well-rounded. - yuvarlatılmış; tamamlanmış.", ""),
    "wordsb2gode.js|abgeschieden": ("abscheiden", "verb", "to separate out, to secrete. - ayırmak, salgılamak.",
                                    "Der Filter soll die Schwebstoffe abscheiden. - Filtre askıdaki maddeleri ayırmalı."),
    "wordsb2gode.js|abgeschüttelt": ("abschütteln", "verb", "to shake off. - silkip atmak, üzerinden atmak.", ""),
    "wordsb2gode.js|abgesondert": ("abgesondert", "adjective", "separated, secluded, isolated. - ayrılmış, tecrit edilmiş.", ""),
    "wordsb2gode.js|abgestanden": ("abstehen", "verb", "to stick out, to protrude; to stand away from. - dışarı fırlamak; uzak durmak.",
                                   "Seine Ohren stehen ein wenig ab. - Kulakları biraz dışarı fırlıktır."),
    "wordsb2gode.js|abgestempelt": ("abstempeln", "verb", "to stamp; to label someone. - damgalamak; yaftalamak.", ""),
    "wordsb2gode.js|abgestimmt": ("abgestimmt", "adjective", "coordinated, matched, tuned to one another. - uyumlu, birbirine göre ayarlanmış.", ""),
    "wordsb2gode.js|ablehnend": ("ablehnend", "adjective", "dismissive, disapproving, negative. - olumsuz, reddeden, onaylamayan.", ""),
    "wordsb2gode.js|abschließend": ("abschließend", "adjective", "final, concluding. - son, kapanış niteliğinde.", ""),
    "wordsb2gode.js|abwehrend": ("abwehrend", "adjective", "defensive, warding off. - savunmacı, savuşturucu.",
                                 "Sie hob abwehrend die Hände. - Savunurcasına ellerini kaldırdı."),
    "wordsb2gode.js|abwertend": ("abwertend", "adjective", "derogatory, pejorative. - aşağılayıcı, küçümseyici.", ""),
    "wordsb2gode.js|affektiert": ("affektiert", "adjective", "affected, mannered. - yapmacık, özentili.", ""),
    "wordsb2gode.js|alkoholisiert": ("alkoholisiert", "adjective", "intoxicated, under the influence of alcohol. - alkollü, sarhoş.", ""),
    "wordsb2gode.js|alle": ("alle", "adjective", "all; (colloquial) all gone, used up. - bütün, hepsi; (günlük dil) bitmiş, tükenmiş.", ""),
    "wordsb2gode.js|andauernd": ("andauernd", "adjective", "continuous, constant, incessant. - sürekli, aralıksız.", ""),
    "wordsb2gode.js|andere": ("andere", "adjective", "other, different. - diğer, başka.", ""),
    "wordsb2gode.js|anerkannt": ("anerkannt", "adjective", "recognized, acknowledged, respected. - tanınmış, kabul görmüş.", ""),
    "wordsb2gode.js|angebracht": ("angebracht", "adjective", "appropriate, fitting; mounted, attached. - uygun, yerinde; takılmış.", ""),
    "wordsb2gode.js|angepasst": ("angepasst", "adjective", "adapted, adjusted; conformist. - uyarlanmış; uyumlu, uysal.", ""),
    "wordsb2gode.js|angespannt": ("angespannt", "adjective", "tense, strained. - gergin, gerilimli.", ""),
    "wordsb2gode.js|angestellt": ("angestellt", "adjective", "employed, salaried. - çalışan, maaşlı.", ""),
    "wordsb2gode.js|angrenzend": ("angrenzend", "adjective", "adjacent, adjoining, bordering. - bitişik, komşu.", ""),
    "wordsb2gode.js|annähernd": ("annähernd", "adjective", "approximate, roughly. - yaklaşık, aşağı yukarı.", ""),
    "wordsb2gode.js|anschließend": ("anschließend", "adjective", "subsequent, following; afterwards. - sonraki; ardından.", ""),
    "wordsb2gode.js|ansprechend": ("ansprechend", "adjective", "appealing, attractive. - çekici, hoşa giden.", ""),
    "wordsb2gode.js|anstrengend": ("anstrengend", "adjective", "strenuous, tiring, exhausting. - yorucu, zahmetli.",
                                   "Die Wanderung war sehr anstrengend. - Yürüyüş çok yorucuydu."),
    "wordsb2gode.js|aufbauend": ("aufbauend", "adjective", "constructive, building upon something. - yapıcı, üzerine kuran.", ""),
    "wordsb2gode.js|aufbrausend": ("aufbrausend", "adjective", "hot-tempered, quick to anger. - çabuk parlayan, öfkeli.", ""),
    "wordsb2gode.js|aufgeblasen": ("aufblasen", "verb", "to inflate, to blow up. - şişirmek.",
                                   "Kannst du den Luftballon aufblasen? - Balonu şişirebilir misin?"),
    "wordsb2gode.js|aufgebracht": ("aufgebracht", "adjective", "upset, incensed, furious. - öfkeli, çok kızmış.", ""),
    "wordsb2gode.js|aufgebraucht": ("aufgebraucht", "adjective", "used up, exhausted. - tükenmiş, bitmiş.", ""),
    "wordsb2gode.js|aufgeklärt": ("aufgeklärt", "adjective", "enlightened; informed. - aydınlanmış; bilgilendirilmiş.", ""),
    "wordsb2gode.js|aufgeladen": ("aufladen", "verb", "to charge (a battery); to load up. - (pili) şarj etmek; yüklemek.", ""),
    "wordsb2gode.js|aufgelauert": ("auflauern", "verb", "to lie in wait for, to ambush. - pusuya yatmak, sinsice beklemek.",
                                   "Er hat ihr am Ausgang aufgelauert. - Çıkışta ona pusu kurdu."),
    "wordsb2gode.js|aufgelöst": ("aufgelöst", "adjective", "dissolved; distraught, in pieces. - çözünmüş; perişan, allak bullak.", ""),
    "wordsb2gode.js|aufgeräumt": ("aufgeräumt", "adjective", "tidy, neat; in good spirits. - toplanmış, düzenli; keyfi yerinde.", ""),
    "wordsb2gode.js|aufgeschnitten": ("aufschneiden", "verb", "to cut open, to slice. - kesip açmak, dilimlemek.", ""),
    "wordsb2gode.js|aufgeweckt": ("aufgeweckt", "adjective", "bright, alert, quick-witted. - zeki, uyanık.", ""),
    "wordsb2gode.js|aufopfernd": ("aufopfernd", "adjective", "self-sacrificing, devoted. - fedakâr, özverili.",
                                  "Sie pflegte ihre Mutter aufopfernd. - Annesine fedakârca baktı."),
    "wordsb2gode.js|aufreizend": ("aufreizend", "adjective", "provocative, alluring. - kışkırtıcı, tahrik edici.", ""),
    "wordsb2gode.js|ausdauernd": ("ausdauernd", "adjective", "persistent, having stamina; perennial. - dayanıklı, azimli; çok yıllık.", ""),
    "wordsb2gode.js|auserkoren": ("auserkiesen", "verb", "to choose, to single out (archaic). - (eskimiş) seçmek, seçip ayırmak.", ""),
    "wordsb2gode.js|ausgebeutet": ("ausgebeutet", "adjective", "exploited. - sömürülmüş.", ""),
    "wordsb2gode.js|ausgebildet": ("ausgebildet", "adjective", "trained, qualified. - eğitimli, yetişmiş.", ""),
    "wordsb2gode.js|ausgedacht": ("ausgedacht", "adjective", "made up, invented. - uydurma, kurgulanmış.", ""),
    "wordsb2gode.js|ausgedehnt": ("ausgedehnt", "adjective", "extensive, expanded, prolonged. - geniş, yayılmış, uzatılmış.", ""),
    "wordsb2gode.js|ausgeführt": ("ausgeführt", "adjective", "carried out, executed. - yerine getirilmiş, uygulanmış.", ""),
    "wordsb2gode.js|ausgeheckt": ("aushecken", "verb", "to hatch, to cook up (a plan). - (plan) kurmak, tezgâhlamak.", ""),
    "wordsb2gode.js|ausgeklügelt": ("ausgeklügelt", "adjective", "sophisticated, ingenious, elaborate. - ustaca tasarlanmış, incelikli.", ""),
    "wordsb2gode.js|ausgelastet": ("ausgelastet", "adjective", "fully occupied, working at capacity. - tam kapasite çalışan, meşgul.", ""),
    "wordsb2gode.js|ausgenommen": ("ausnehmen", "verb", "to gut (an animal); to exempt. - (hayvanı) temizlemek; hariç tutmak.", ""),
    "wordsb2gode.js|ausgerechnet": ("ausgerechnet", "adjective", "of all things, of all people. - hem de, ille de, tam da.", ""),
    "wordsb2gode.js|ausgereift": ("ausgereift", "adjective", "mature, fully developed. - olgunlaşmış, gelişmiş.", ""),
    "wordsb2gode.js|ausgespannt": ("ausspannen", "verb", "to relax, to take a break; to unhitch. - dinlenmek, mola vermek; koşumdan çıkarmak.",
                                   "Am Wochenende will ich einfach mal ausspannen. - Hafta sonu sadece biraz dinlenmek istiyorum."),
    "wordsb2gode.js|ausgewachsen": ("auswachsen", "verb", "to grow to full size; to develop into. - tam boyuna erişmek; dönüşmek.", ""),
    "wordsb2gode.js|ausgezeichnet": ("ausgezeichnet", "adjective", "excellent, outstanding. - mükemmel, üstün.", ""),
    "wordsb2gode.js|ausreichend": ("ausreichend", "adjective", "sufficient, adequate. - yeterli.", ""),
    "wordsb2gode.js|ausverkauft": ("ausverkauft", "adjective", "sold out. - tükenmiş, biletleri satılmış.", ""),
    "wordsb2gode.js|bedeckt": ("bedeckt", "adjective", "covered; overcast. - örtülü, kaplı; bulutlu.", ""),
    "wordsb2gode.js|bedeutend": ("bedeutend", "adjective", "significant, important. - önemli, kayda değer.", ""),
    "wordsb2gode.js|bedingt": ("bedingt", "adjective", "conditional; limited, qualified. - koşullu; sınırlı, kısmen.", ""),
    "wordsb2gode.js|bedrückend": ("bedrückend", "adjective", "oppressive, depressing. - iç karartıcı, ezici.", ""),
    "wordsb2gode.js|bedrückt": ("bedrückt", "adjective", "depressed, downcast. - keyifsiz, üzgün.", ""),
    "wordsb2gode.js|eingebrannt": ("einbrennen", "verb", "to burn in, to sear in. - dağlamak, iyice işlemek.", ""),
    "wordsb2gode.js|festgebunden": ("festbinden", "verb", "to tie down, to fasten. - bağlamak, sabitlemek.", ""),
    "wordsb2gode.js|gebraucht": ("gebraucht", "adjective", "used, second-hand. - kullanılmış, ikinci el.",
                                 "Er hat sich ein gebrauchtes Auto gekauft. - Kendine ikinci el bir araba aldı."),
    "wordsb2gode.js|herumgeführt": ("herumführen", "verb", "to show around; to lead astray. - gezdirmek; oyalamak.", ""),
    "wordsb2gode.js|hingekommen": ("hinkommen", "verb", "to get there; to end up somewhere. - oraya varmak; bir yere düşmek.", ""),
    "wordsb2gode.js|hingesehen": ("hinsehen", "verb", "to look, to look closely. - bakmak, dikkatle bakmak.", ""),
    "wordsb2gode.js|nachgeforscht": ("nachforschen", "verb", "to investigate, to inquire into. - araştırmak, soruşturmak.", ""),
    "wordsb2gode.js|nachgestellt": ("nachstellen", "verb", "to reenact, to recreate; to stalk. - yeniden canlandırmak; peşine düşmek.",
                                    "Die Szene wurde für den Film genau nachgestellt. - Sahne film için birebir yeniden canlandırıldı."),
    "wordsb2gode.js|umgeworfen": ("umwerfen", "verb", "to knock over; to bowl over, to stun. - devirmek; sarsmak, çok etkilemek.", ""),
    "wordsb2gode.js|vergönnt": ("vergönnen", "verb", "to grant, to allow someone something. - bahşetmek, nasip etmek.", ""),
    "wordsb2gode.js|verschwitzt": ("verschwitzen", "verb", "to sweat through; to clean forget. - ter içinde bırakmak; unutuvermek.", ""),
    "wordsb2gode.js|vorbestimmt": ("vorbestimmen", "verb", "to predetermine, to preordain. - önceden belirlemek, alnına yazmak.", ""),
    "wordsb2gode.js|vorgefunden": ("vorfinden", "verb", "to find, to come upon. - bulmak, hazır bulmak.", ""),
    "wordsb2gode.js|vorgesungen": ("vorsingen", "verb", "to sing to someone; to audition by singing. - birine şarkı söylemek; sesle seçmeye katılmak.", ""),
    "wordsb2gode.js|vorverlegt": ("vorverlegen", "verb", "to bring forward, to move up (a date). - (tarihi) öne almak.", ""),
    "wordsb2gode.js|weggeschafft": ("wegschaffen", "verb", "to remove, to clear away. - kaldırmak, ortadan kaldırmak.", ""),
    "wordsb2gode.js|zerfleischt": ("zerfleischen", "verb", "to maul, to tear to pieces. - parçalamak, paramparça etmek.", ""),
    "wordsb2gode.js|zurückgeschlagen": ("zurückschlagen", "verb", "to strike back, to repel. - karşılık vermek, püskürtmek.",
                                        "Die Armee hat den Angriff zurückgeschlagen. - Ordu saldırıyı püskürttü."),

    # ===== wordsc1gode.js
    "wordsc1gode.js|Eindringen": ("Eindringen", "noun", "penetration, intrusion, incursion. - sızma, içeri girme, nüfuz etme.",
                                  "Das Eindringen des Wassers muss verhindert werden. - Suyun içeri sızması önlenmelidir."),
    "wordsc1gode.js|Eingreifen": ("Eingreifen", "noun", "intervention, stepping in. - müdahale, araya girme.",
                                  "Nur sein schnelles Eingreifen hat Schlimmeres verhindert. - Daha kötüsünü yalnızca onun hızlı müdahalesi önledi."),
    "wordsc1gode.js|Einkommen": ("Einkommen", "noun", "income. - gelir.", ""),
    "wordsc1gode.js|Entgegenkommen": ("Entgegenkommen", "noun", "obligingness, accommodation, concession. - kolaylık gösterme, jest, taviz.", ""),
    "wordsc1gode.js|Entsetzen": ("Entsetzen", "noun", "horror, dismay. - dehşet, korku.", ""),
    "wordsc1gode.js|Entzücken": ("Entzücken", "noun", "delight, rapture. - büyük sevinç, hayranlık.", ""),
    "wordsc1gode.js|Ernten": ("ernten", "verb", "to harvest, to reap. - hasat etmek, biçmek.", ""),
    "wordsc1gode.js|Erstaunen": ("Erstaunen", "noun", "astonishment, amazement. - şaşkınlık, hayret.", ""),
    "wordsc1gode.js|Essen": ("Essen", "noun", "food; meal. - yemek; öğün.", ""),
    "wordsc1gode.js|Finanzen": ("Finanz", "noun", "finance, public finances. - maliye, finans.",
                                "Er studiert Finanz und Rechnungswesen. - Maliye ve muhasebe okuyor."),
    "wordsc1gode.js|Flattern": ("flattern", "verb", "to flutter, to flap. - kanat çırpmak, dalgalanmak.", ""),
    "wordsc1gode.js|Flusen": ("Fluse", "noun", "piece of fluff, lint. - tüy, pamukçuk.",
                              "Auf dem schwarzen Pullover klebte eine weiße Fluse. - Siyah kazakta beyaz bir tüy vardı."),
    "wordsc1gode.js|Flüstern": ("flüstern", "verb", "to whisper. - fısıldamak.", ""),
    "wordsc1gode.js|Funkeln": ("funkeln", "verb", "to sparkle, to twinkle. - parıldamak, ışıldamak.", ""),
    "wordsc1gode.js|Versilbern": ("versilbern", "verb", "to silver-plate; to turn into cash. - gümüş kaplamak; paraya çevirmek.", ""),
    "wordsc1gode.js|abfallend": ("abfallend", "adjective", "sloping, descending; declining. - eğimli, inişli; azalan.",
                                 "Der Garten liegt an einem leicht abfallenden Hang. - Bahçe hafif eğimli bir yamaçtadır."),
    "wordsc1gode.js|abgeknöpft": ("abknöpfen", "verb", "to unbutton; to wheedle money out of someone. - düğmesini çözmek; (para) koparmak.", ""),
    "wordsc1gode.js|abgemildert": ("abgemildert", "adjective", "mitigated, toned down. - hafifletilmiş, yumuşatılmış.",
                                   "Die Kritik erschien in stark abgemilderter Form. - Eleştiri epeyce yumuşatılmış biçimde yayımlandı."),
    "wordsc1gode.js|abgemurkst": ("abmurksen", "verb", "to bump off, to do in. - temizlemek, işini bitirmek.", ""),
    "wordsc1gode.js|abgerackert": ("abrackern", "verb", "to slave away, to toil. - eşek gibi çalışmak, didinmek.", ""),
    "wordsc1gode.js|abgeschrägt": ("abgeschrägt", "adjective", "bevelled, chamfered, sloped. - eğik kesilmiş, pahlı.",
                                   "Die Kanten der Platte sind abgeschrägt. - Levhanın kenarları pahlanmıştır."),
    "wordsc1gode.js|abgetastet": ("abtasten", "verb", "to feel, to palpate; to scan. - yoklamak, elle muayene etmek; taramak.",
                                  "Der Arzt hat den Bauch vorsichtig abgetastet. - Doktor karnı dikkatlice yokladı."),
    "wordsc1gode.js|abgewirtschaftet": ("abgewirtschaftet", "adjective", "run-down, played out, bankrupt. - iflas etmiş, çökmüş.", ""),
    "wordsc1gode.js|abweichend": ("abweichend", "adjective", "deviating, differing, divergent. - farklı, sapan.",
                                  "Er vertritt eine abweichende Meinung. - Farklı bir görüşü savunuyor."),
    "wordsc1gode.js|alliiert": ("alliiert", "adjective", "allied. - müttefik.", ""),
    "wordsc1gode.js|angefüllt": ("anfüllen", "verb", "to fill up. - doldurmak.",
                                 "Der Keller war mit altem Gerümpel angefüllt. - Bodrum eski döküntülerle doluydu."),
    "wordsc1gode.js|angegliedert": ("angegliedert", "adjective", "affiliated, attached to. - bağlı, ilhak edilmiş.",
                                    "Das Institut ist der Universität angegliedert. - Enstitü üniversiteye bağlıdır."),
    "wordsc1gode.js|angekleidet": ("ankleiden", "verb", "to dress, to get dressed. - giydirmek, giyinmek.", ""),
    "wordsc1gode.js|angeklopft": ("anklopfen", "verb", "to knock at a door. - kapıyı çalmak.", ""),
    "wordsc1gode.js|angestaut": ("anstauen", "verb", "to dam up; to build up, to accumulate. - biriktirmek, birikmek.",
                                 "Über Jahre hatte sich viel Wut angestaut. - Yıllar içinde çok öfke birikmişti."),
    "wordsc1gode.js|anheimelnd": ("anheimelnd", "adjective", "cosy, homely, quaint. - insana sıcak gelen, iç açıcı.",
                                  "Die kleine Stube wirkte sehr anheimelnd. - Küçük oda insana çok sıcak geliyordu."),
    "wordsc1gode.js|anklagend": ("anklagend", "adjective", "accusatory, reproachful. - suçlayıcı, sitemkâr.",
                                 "Sie sah ihn anklagend an. - Ona suçlayıcı bir bakış attı."),
    "wordsc1gode.js|ausgehöhlt": ("aushöhlen", "verb", "to hollow out; to erode, to undermine. - oymak, içini boşaltmak; aşındırmak.", ""),
    "wordsc1gode.js|ausgemergelt": ("ausgemergelt", "adjective", "emaciated, gaunt, wasted. - bitkin, sıska, kadidi çıkmış.",
                                    "Der Gefangene war völlig ausgemergelt. - Tutsak bir deri bir kemik kalmıştı."),
    "wordsc1gode.js|ausgerückt": ("ausrücken", "verb", "to be called out (fire brigade); to run off. - (itfaiye) göreve çıkmak; sıvışmak.", ""),
    "wordsc1gode.js|ausgeschickt": ("ausschicken", "verb", "to send out. - dışarı göndermek.",
                                    "Man hat Boten in alle Richtungen ausgeschickt. - Her yöne haberciler gönderildi."),
    "wordsc1gode.js|ausgeschlachtet": ("ausschlachten", "verb", "to cannibalize for parts; to exploit for gain. - parçalarına ayırmak; sömürerek yararlanmak.",
                                       "Das alte Auto wurde komplett ausgeschlachtet. - Eski araba tamamen parçalarına ayrıldı."),
    "wordsc1gode.js|beeinflussend": ("beeinflussend", "adjective", "influencing, having an effect on. - etkileyen, tesir eden.",
                                     "Der Preis ist der stärkste beeinflussende Faktor. - Fiyat, en güçlü etkileyen etkendir."),
    "wordsc1gode.js|beeinflusst": ("beeinflusst", "adjective", "influenced, affected. - etkilenmiş.", ""),
    "wordsc1gode.js|beflissen": ("befleißen", "verb", "to apply oneself, to take pains. - kendini vermek, gayret etmek.", ""),
    "wordsc1gode.js|befriedigt": ("befriedigt", "adjective", "satisfied, content. - memnun, tatmin olmuş.", ""),
    "wordsc1gode.js|befugt": ("befugt", "adjective", "authorized, entitled. - yetkili, izinli.", ""),
    "wordsc1gode.js|begabt": ("begabt", "adjective", "gifted, talented. - yetenekli.", ""),
    "wordsc1gode.js|beginnend": ("beginnend", "adjective", "beginning, incipient. - başlayan, başlangıç hâlindeki.",
                                 "Er zeigt Anzeichen einer beginnenden Erkältung. - Başlayan bir soğuk algınlığının belirtilerini gösteriyor."),
    "wordsc1gode.js|begleitend": ("begleitend", "adjective", "accompanying, concomitant. - eşlik eden, yandaş.",
                                  "Zum Kurs gibt es ein begleitendes Übungsheft. - Kursa eşlik eden bir alıştırma kitapçığı var."),
    "wordsc1gode.js|beglückt": ("beglückt", "adjective", "overjoyed, delighted. - çok mutlu, sevinçli.", ""),
    "wordsc1gode.js|begrenzt": ("begrenzt", "adjective", "limited, restricted. - sınırlı, kısıtlı.",
                                "Die Zahl der Plätze ist stark begrenzt. - Yer sayısı çok sınırlıdır."),
    "wordsc1gode.js|begründend": ("begründend", "adjective", "justifying, giving reasons, causal. - gerekçelendiren, nedensel.",
                                  "Der Aufsatz endet mit einem begründenden Absatz. - Yazı, gerekçelendiren bir paragrafla biter."),
    "wordsc1gode.js|beheimatet": ("beheimatet", "adjective", "native to, at home in. - yerleşik, yurt edinmiş.", ""),
    "wordsc1gode.js|beherrschend": ("beherrschend", "adjective", "dominant, commanding, controlling. - baskın, hâkim.",
                                    "Der Turm ist das beherrschende Bauwerk der Stadt. - Kule, kentin hâkim yapısıdır."),
    "wordsc1gode.js|behindert": ("behindert", "adjective", "disabled; (offensive slang) idiotic. - engelli; (kaba argo) saçma.", ""),
    "wordsc1gode.js|bekannt": ("bekannt", "adjective", "well-known, familiar. - tanınmış, bilinen.", ""),
    "wordsc1gode.js|belehrend": ("belehrend", "adjective", "didactic, preachy, instructive. - öğretici, nasihatçi.",
                                 "Sein belehrender Ton ging allen auf die Nerven. - Nasihatçi tonu herkesin sinirine dokundu."),
    "wordsc1gode.js|beleidigend": ("beleidigend", "adjective", "offensive, insulting. - hakaret edici, kırıcı.", ""),
    "wordsc1gode.js|bemitleidet": ("bemitleiden", "verb", "to pity, to feel sorry for. - acımak, haline üzülmek.", ""),
    "wordsc1gode.js|berauscht": ("berauscht", "adjective", "intoxicated, elated. - sarhoş, mest olmuş.", ""),
    "wordsc1gode.js|berechtigt": ("berechtigt", "adjective", "entitled, authorized; justified. - hak sahibi, yetkili; haklı.", ""),
    "wordsc1gode.js|beruhigend": ("beruhigend", "adjective", "soothing, reassuring, calming. - yatıştırıcı, iç rahatlatıcı.", ""),
    "wordsc1gode.js|beschreibend": ("beschreibend", "adjective", "descriptive. - betimleyici, tasvir edici.", ""),
    "wordsc1gode.js|beschränkt": ("beschränkt", "adjective", "limited, restricted; narrow-minded. - sınırlı; dar kafalı.", ""),
    "wordsc1gode.js|beschädigt": ("beschädigt", "adjective", "damaged. - hasarlı, zarar görmüş.", ""),
    "wordsc1gode.js|beschämend": ("beschämend", "adjective", "shameful, embarrassing. - utanç verici.", ""),
    "wordsc1gode.js|beschützend": ("beschützend", "adjective", "protective. - koruyucu, kollayıcı.", ""),
    "wordsc1gode.js|bestehend": ("bestehend", "adjective", "existing; consisting of. - mevcut; -den oluşan.", ""),
    "wordsc1gode.js|bestimmt": ("bestimmt", "adjective", "certain, definite; firm, determined. - belirli, kesin; kararlı.",
                                "Er sprach in einem sehr bestimmten Ton. - Çok kararlı bir tonda konuştu."),
    "wordsc1gode.js|beurkundet": ("beurkundet", "adjective", "certified, officially recorded. - belgelenmiş, resmen tescilli.",
                                  "Die Geburt wurde standesamtlich beurkundet. - Doğum nüfus dairesince tescil edildi."),
    "wordsc1gode.js|bewaldet": ("bewaldet", "adjective", "wooded, forested. - ormanlık, ağaçlık.", ""),
    "wordsc1gode.js|bewandert": ("bewandert", "adjective", "well-versed, knowledgeable. - bilgili, uzman.", ""),
    "wordsc1gode.js|bewährt": ("bewährt", "adjective", "proven, tried and tested. - denenmiş, güvenilir.", ""),
    "wordsc1gode.js|beängstigend": ("beängstigend", "adjective", "frightening, alarming. - ürkütücü, endişe verici.", ""),
    "wordsc1gode.js|bindend": ("bindend", "adjective", "binding. - bağlayıcı.",
                               "Diese Zusage ist rechtlich bindend. - Bu taahhüt hukuken bağlayıcıdır."),
    "wordsc1gode.js|blendend": ("blendend", "adjective", "dazzling; splendid. - göz kamaştırıcı; harika.", ""),
    "wordsc1gode.js|das": ("das", "adjective", "the (neuter); that, which. - (yansız) belirli tanımlık; o, ki o.", ""),
    "wordsc1gode.js|dediziert": ("dediziert", "adjective", "dedicated, reserved for one purpose. - özel olarak ayrılmış, adanmış.",
                                 "Der Dienst läuft auf einem dedizierten Server. - Hizmet, özel bir sunucuda çalışıyor."),
    "wordsc1gode.js|demotivierend": ("demotivierend", "adjective", "demotivating, discouraging. - motivasyon kırıcı, cesaret kırıcı.", ""),
    "wordsc1gode.js|designiert": ("designiert", "adjective", "designated, incoming (in a role). - atanmış, göreve gelecek olan.", ""),
    "wordsc1gode.js|desorientiert": ("desorientieren", "verb", "to disorient, to confuse. - yönünü şaşırtmak, kafasını karıştırmak.", ""),
    "wordsc1gode.js|diese": ("diese", "adjective", "this, these. - bu, bunlar.", ""),
    "wordsc1gode.js|distanziert": ("distanziert", "adjective", "distant, aloof, detached. - mesafeli, soğuk.", ""),
    "wordsc1gode.js|diverse": ("diverse", "adjective", "various, several. - çeşitli, muhtelif.", ""),
    "wordsc1gode.js|doppelt": ("doppelt", "adjective", "double, twofold. - iki kat, çift.", ""),
    "wordsc1gode.js|dringend": ("dringend", "adjective", "urgent, pressing. - acil, ivedi.", ""),
    "wordsc1gode.js|duftend": ("duftend", "adjective", "fragrant, sweet-smelling. - mis kokulu.", ""),
    "wordsc1gode.js|durchdacht": ("durchdacht", "adjective", "well thought out. - iyi düşünülmüş.", ""),
    "wordsc1gode.js|durchgearbeitet": ("durcharbeiten", "verb", "to work through without a break. - ara vermeden çalışmak.", ""),
    "wordsc1gode.js|durchgespielt": ("durchspielen", "verb", "to play through, to run through. - baştan sona oynamak, gözden geçirmek.", ""),
    "wordsc1gode.js|durchscheinend": ("durchscheinend", "adjective", "translucent. - yarı saydam.", ""),
    "wordsc1gode.js|eingearbeitet": ("eingearbeitet", "adjective", "trained in, up to speed; incorporated. - işe alışmış; içine işlenmiş.",
                                     "Der neue Kollege ist gut eingearbeitet. - Yeni iş arkadaşı işe iyice alıştı."),
    "wordsc1gode.js|eingebaut": ("eingebaut", "adjective", "built-in, integrated. - dahili, gömülü.", ""),
    "wordsc1gode.js|eingebildet": ("eingebildet", "adjective", "conceited, stuck-up; imagined. - kendini beğenmiş; hayalî.", ""),
    "wordsc1gode.js|eingedrückt": ("eindrücken", "verb", "to push in, to dent. - içeri bastırmak, göçürmek.",
                                   "Der Aufprall hat die Tür eingedrückt. - Çarpma kapıyı göçürdü."),
    "wordsc1gode.js|eingefasst": ("eingefasst", "adjective", "bordered, framed, set (a gem). - çerçeveli, kenarı işlenmiş.", ""),
    "wordsc1gode.js|eingekehrt": ("einkehren", "verb", "to stop off at an inn. - bir handa mola vermek.", ""),
    "wordsc1gode.js|eingeschläfert": ("einschläfern", "verb", "to lull to sleep; to put an animal down. - uyutmak; (hayvanı) uyutarak öldürmek.", ""),
    "wordsc1gode.js|eingewandert": ("eingewandert", "adjective", "immigrated, immigrant. - göç etmiş, göçmen.", ""),
    "wordsc1gode.js|eingliedernd": ("eingliedernd", "adjective", "integrating, incorporating. - bütünleştirici, katan.",
                                    "Die Schule verfolgt einen eingliedernden Ansatz. - Okul bütünleştirici bir yaklaşım izliyor."),
    "wordsc1gode.js|eingreifend": ("eingreifend", "adjective", "intervening, far-reaching. - müdahaleci, köklü.",
                                   "Die Reform brachte tief eingreifende Änderungen. - Reform, köklü değişiklikler getirdi."),
    "wordsc1gode.js|einige": ("einige", "adjective", "some, a few. - bazı, birkaç.", ""),
    "wordsc1gode.js|einschläfernd": ("einschläfernd", "adjective", "soporific, sleep-inducing; boring. - uyku getiren; sıkıcı.", ""),
    "wordsc1gode.js|entfernt": ("entfernt", "adjective", "distant, remote; away. - uzak, ırak.", ""),
    "wordsc1gode.js|entgegengenommen": ("entgegennehmen", "verb", "to accept, to receive. - kabul etmek, teslim almak.", ""),
    "wordsc1gode.js|entgegengesetzt": ("entgegengesetzt", "adjective", "opposite, contrary. - zıt, karşıt.", ""),
    "wordsc1gode.js|entgegenkommend": ("entgegenkommend", "adjective", "obliging, accommodating; oncoming. - yardımsever, anlayışlı; karşıdan gelen.", ""),
    "wordsc1gode.js|enthemmt": ("enthemmt", "adjective", "uninhibited, disinhibited. - ketlenmemiş, pervasız.",
                                "Nach ein paar Gläsern wirkte er völlig enthemmt. - Birkaç kadehten sonra tamamen pervasız görünüyordu."),
    "wordsc1gode.js|entkräftet": ("entkräftet", "adjective", "exhausted, weakened; refuted. - bitkin, güçsüz; çürütülmüş.", ""),
    "wordsc1gode.js|entsprechend": ("entsprechend", "adjective", "corresponding, appropriate. - uygun, karşılık gelen.", ""),
    "wordsc1gode.js|entzündet": ("entzündet", "adjective", "inflamed; ignited. - iltihaplı; tutuşmuş.",
                                 "Die Wunde ist entzündet. - Yara iltihaplandı."),
    "wordsc1gode.js|ergänzend": ("ergänzend", "adjective", "supplementary, additional. - tamamlayıcı, ek.", ""),
    "wordsc1gode.js|erzählend": ("erzählend", "adjective", "narrative. - anlatısal, öykülemeci.",
                                 "Der Roman ist ein erzählendes Kunstwerk. - Roman, anlatısal bir sanat eseridir."),
    "wordsc1gode.js|exaltiert": ("exaltiert", "adjective", "overexcited, affected, exalted. - aşırı coşkulu, abartılı.", ""),
    "wordsc1gode.js|faszinierend": ("faszinierend", "adjective", "fascinating. - büyüleyici.", ""),
    "wordsc1gode.js|festgelegt": ("festgelegt", "adjective", "fixed, set, stipulated. - belirlenmiş, sabit.", ""),
    "wordsc1gode.js|forciert": ("forciert", "adjective", "forced, strained. - zorlama, yapmacık.", ""),
    "wordsc1gode.js|fortschreitend": ("fortschreitend", "adjective", "progressive, advancing. - ilerleyen, gitgide artan.", ""),
    "wordsc1gode.js|gebildet": ("gebildet", "adjective", "educated, cultured. - eğitimli, kültürlü.",
                                "Sie ist eine sehr gebildete Frau. - O, çok kültürlü bir kadın."),
    "wordsc1gode.js|gedatet": ("daten", "verb", "to date someone. - biriyle çıkmak, randevulaşmak.", ""),
    "wordsc1gode.js|gedeckt": ("gedeckt", "adjective", "covered; muted (colour); set (table). - örtülü; soluk (renk); kurulu (masa).", ""),
    "wordsc1gode.js|gedämpft": ("gedämpft", "adjective", "muffled, subdued; steamed. - boğuk, kısık; buharda pişmiş.",
                                "Aus dem Nebenzimmer hörte man gedämpfte Stimmen. - Yan odadan boğuk sesler geliyordu."),
    "wordsc1gode.js|gefragt": ("gefragt", "adjective", "in demand, sought after. - aranan, rağbet gören.",
                               "Gute Handwerker sind sehr gefragt. - İyi ustalar çok aranıyor."),
    "wordsc1gode.js|gefüllt": ("gefüllt", "adjective", "filled, stuffed. - dolu, doldurulmuş.", ""),
    "wordsc1gode.js|gehasst": ("gehasst", "adjective", "hated, detested. - nefret edilen.", ""),
    "wordsc1gode.js|geheiligt": ("geheiligt", "adjective", "hallowed, sanctified. - kutsanmış, mukaddes.", ""),
    "wordsc1gode.js|gehäuft": ("gehäuft", "adjective", "heaped; frequent, accumulated. - tepeleme; sık sık olan, birikmiş.", ""),
    "wordsc1gode.js|gekürzt": ("gekürzt", "adjective", "shortened, abridged, cut. - kısaltılmış, kesilmiş.", ""),
    "wordsc1gode.js|gelehrt": ("gelehrt", "adjective", "learned, scholarly. - âlim, bilgin.",
                               "Er schrieb einen sehr gelehrten Aufsatz. - Çok bilgince bir makale yazdı."),
    "wordsc1gode.js|gemischt": ("gemischt", "adjective", "mixed. - karışık.", ""),
    "wordsc1gode.js|gemäßigt": ("gemäßigt", "adjective", "moderate; temperate. - ılımlı; ılıman.", ""),
    "wordsc1gode.js|genervt": ("genervt", "adjective", "annoyed, irritated. - sinirli, bunalmış.", ""),
    "wordsc1gode.js|genormt": ("genormt", "adjective", "standardized. - standartlaştırılmış.", ""),
    "wordsc1gode.js|geordnet": ("geordnet", "adjective", "orderly, arranged, sorted. - düzenli, sıralanmış.", ""),
    "wordsc1gode.js|gepfeffert": ("gepfeffert", "adjective", "peppered; steep, stiff (price, penalty). - biberli; fahiş, ağır.", ""),
    "wordsc1gode.js|geplant": ("geplant", "adjective", "planned, scheduled. - planlanmış.", ""),
    "wordsc1gode.js|geprüft": ("geprüft", "adjective", "tested, certified, examined. - denetlenmiş, belgeli.", ""),
    "wordsc1gode.js|geputzt": ("geputzt", "adjective", "cleaned, polished. - temizlenmiş, parlatılmış.", ""),
    "wordsc1gode.js|geriffelt": ("geriffelt", "adjective", "grooved, fluted, ribbed. - yivli, oluklu.",
                                 "Der Griff ist geriffelt, damit er nicht rutscht. - Sap, kaymasın diye yivlidir."),
    "wordsc1gode.js|gerüstet": ("gerüstet", "adjective", "prepared, equipped. - hazırlıklı, donanımlı.", ""),
    "wordsc1gode.js|geschickt": ("geschickt", "adjective", "skilful, deft, clever. - becerikli, hünerli.", ""),
    "wordsc1gode.js|geschröpft": ("geschröpft", "adjective", "fleeced, bled dry. - kazıklanmış, sağılmış.",
                                  "Die Kunden werden mit hohen Gebühren geschröpft. - Müşteriler yüksek ücretlerle kazıklanıyor."),
    "wordsc1gode.js|geschützt": ("geschützt", "adjective", "protected, sheltered. - korunmuş, korumalı.", ""),
    "wordsc1gode.js|gesellt": ("gesellen", "verb", "to join, to associate with. - katılmak, arkadaşlık etmek.", ""),
    "wordsc1gode.js|gestresst": ("gestresst", "adjective", "stressed, stressed out. - stresli, gergin.", ""),
    "wordsc1gode.js|gestrichelt": ("gestrichelt", "adjective", "dashed, drawn as a broken line. - kesik çizgili.",
                                   "Die Grenze ist auf der Karte gestrichelt eingezeichnet. - Sınır haritada kesik çizgiyle gösterilmiştir."),
    "wordsc1gode.js|gestört": ("gestört", "adjective", "disturbed, disrupted; mentally disturbed. - bozulmuş, aksamış; ruhen dengesiz.", ""),
    "wordsc1gode.js|gesättigt": ("gesättigt", "adjective", "saturated; satiated. - doymuş; tok.", ""),
    "wordsc1gode.js|getakelt": ("getakelt", "adjective", "rigged (a ship); dolled up. - donanımlı (gemi); süslenip püslenmiş.",
                                "Das Schiff war voll getakelt. - Gemi tam donanımlıydı."),
    "wordsc1gode.js|getürkt": ("türken", "verb", "to fake, to rig. - sahtesini yapmak, uydurmak.", ""),
    "wordsc1gode.js|gewagt": ("gewagt", "adjective", "daring, bold, risqué. - cüretkâr, cesur.", ""),
    "wordsc1gode.js|gewandt": ("gewandt", "adjective", "adroit, nimble, articulate. - becerikli, çevik, ağzı laf yapan.", ""),
    "wordsc1gode.js|gezackt": ("gezackt", "adjective", "jagged, serrated. - tırtıklı, testere ağızlı.",
                               "Das Blatt hat einen gezackten Rand. - Yaprağın kenarı tırtıklıdır."),
    "wordsc1gode.js|gezeichnet": ("gezeichnet", "adjective", "drawn; marked by suffering. - çizilmiş; (acıyla) damgalanmış.", ""),
    "wordsc1gode.js|gezielt": ("gezielt", "adjective", "targeted, deliberate. - hedefli, bilinçli.",
                               "Wir brauchen gezielte Maßnahmen. - Hedefli önlemlere ihtiyacımız var."),
    "wordsc1gode.js|gezähmt": ("gezähmt", "adjective", "tamed, domesticated. - evcilleştirilmiş, ehlileştirilmiş.",
                               "Ein gezähmter Falke saß auf seinem Arm. - Kolunda evcilleştirilmiş bir şahin duruyordu."),
    "wordsc1gode.js|gleichgestellt": ("gleichstellen", "verb", "to put on an equal footing, to grant equal status. - eşit saymak, eşit konuma getirmek.",
                                      "Beide Abschlüsse wurden rechtlich gleichgestellt. - Her iki diploma hukuken eşit sayıldı."),
    "wordsc1gode.js|grundlegend": ("grundlegend", "adjective", "fundamental, basic. - temel, esaslı.", ""),
    "wordsc1gode.js|hemmend": ("hemmend", "adjective", "inhibiting, restraining. - engelleyici, ketleyici.",
                               "Diese Vorschrift wirkt hemmend auf die Forschung. - Bu kural araştırma üzerinde engelleyici etki yapıyor."),
    "wordsc1gode.js|herabgesetzt": ("herabgesetzt", "adjective", "reduced, marked down; belittled. - indirimli; küçümsenmiş.", ""),
    "wordsc1gode.js|herausfordernd": ("herausfordernd", "adjective", "challenging, provocative, defiant. - meydan okuyan, zorlayıcı.", ""),
    "wordsc1gode.js|hineingesteckt": ("hineinstecken", "verb", "to put into; to invest effort or money in. - içine koymak; (emek, para) yatırmak.", ""),
    "wordsc1gode.js|innere": ("innere", "adjective", "inner, internal. - iç, dahilî.", ""),
    "wordsc1gode.js|interessiert": ("interessiert", "adjective", "interested. - ilgili, ilgi duyan.", ""),
    "wordsc1gode.js|irgendeiner": ("irgendeiner", "adjective", "some, any one. - herhangi biri, herhangi bir.", ""),
    "wordsc1gode.js|lebend": ("lebend", "adjective", "living, alive. - yaşayan, canlı.", ""),
    "wordsc1gode.js|leitend": ("leitend", "adjective", "leading, managerial; conductive. - yönetici; iletken.",
                               "Sie ist als leitende Ärztin tätig. - Başhekim olarak çalışıyor."),
    "wordsc1gode.js|letzter": ("letzter", "adjective", "last, latest, final. - son, sonuncu.", ""),
    "wordsc1gode.js|losgemacht": ("losmachen", "verb", "to untie, to detach, to free. - çözmek, ayırmak, kurtarmak.", ""),
    "wordsc1gode.js|missfallend": ("missfallend", "adjective", "displeasing, disagreeable. - hoşa gitmeyen, rahatsız edici.",
                                   "Er machte eine missfallende Bemerkung. - Hoşa gitmeyen bir yorum yaptı."),
    "wordsc1gode.js|nachwachsend": ("nachwachsend", "adjective", "regrowing, renewable. - yeniden büyüyen, yenilenebilir.",
                                    "Holz ist ein nachwachsender Rohstoff. - Odun, yenilenebilir bir hammaddedir."),
    "wordsc1gode.js|passend": ("passend", "adjective", "suitable, matching, fitting. - uygun, yakışan.",
                               "Das ist genau die passende Größe. - Tam da uygun beden bu."),
    "wordsc1gode.js|prädestiniert": ("prädestiniert", "adjective", "predestined, ideally suited. - önceden belirlenmiş, biçilmiş kaftan.",
                                     "Für diese Aufgabe ist er geradezu prädestiniert. - Bu görev ona adeta biçilmiş kaftan."),
    "wordsc1gode.js|quälend": ("quälend", "adjective", "tormenting, agonizing. - eziyet verici, azap dolu.",
                               "Das Warten war quälend lang. - Bekleyiş eziyet verici derecede uzundu."),
    "wordsc1gode.js|retardiert": ("retardiert", "adjective", "delayed in development, retarded. - gelişimi gecikmiş.",
                                  "Die Entwicklung des Kindes war leicht retardiert. - Çocuğun gelişimi biraz gecikmişti."),
    "wordsc1gode.js|schwankend": ("schwankend", "adjective", "swaying, wobbling; fluctuating. - sallanan; dalgalanan.", ""),
    "wordsc1gode.js|telegrafiert": ("telegrafieren", "verb", "to telegraph, to wire. - telgraf çekmek.",
                                    "Er hat die Nachricht sofort telegrafiert. - Haberi hemen telgrafla bildirdi."),
    "wordsc1gode.js|verblüht": ("verblüht", "adjective", "faded, past its bloom. - solmuş, çiçeği geçmiş.", ""),
    "wordsc1gode.js|verfrüht": ("verfrüht", "adjective", "premature, too early. - erken, vaktinden önce.", ""),
    "wordsc1gode.js|vorbeigelaufen": ("vorbeilaufen", "verb", "to walk or run past. - yanından geçip gitmek.", ""),
    "wordsc1gode.js|vorbestellt": ("vorbestellen", "verb", "to book in advance, to preorder. - önceden ayırtmak, ön sipariş vermek.", ""),
    "wordsc1gode.js|vorgebracht": ("vorbringen", "verb", "to put forward, to advance an argument. - ileri sürmek, öne sürmek.", ""),
    "wordsc1gode.js|vorgeschoben": ("vorschieben", "verb", "to push forward; to use as a pretext. - öne itmek; bahane olarak öne sürmek.",
                                    "Er hat einen Termin vorgeschoben, um früher zu gehen. - Erken çıkmak için bahane olarak bir randevu öne sürdü."),
    "wordsc1gode.js|vorgesetzt": ("vorsetzen", "verb", "to place in front of someone, to serve up. - önüne koymak, ikram etmek.", ""),
    "wordsc1gode.js|weggefegt": ("wegfegen", "verb", "to sweep away. - süpürüp atmak.",
                                 "Der Sturm hat alles vom Tisch weggefegt. - Fırtına masadaki her şeyi süpürüp attı."),
    "wordsc1gode.js|weggetragen": ("wegtragen", "verb", "to carry away. - taşıyıp götürmek.", ""),
    "wordsc1gode.js|zugedrückt": ("zudrücken", "verb", "to press shut; to turn a blind eye. - bastırıp kapatmak; göz yummak.", ""),
    "wordsc1gode.js|zugefallen": ("zufallen", "verb", "to fall shut; to fall to someone. - kendiliğinden kapanmak; (pay, görev) düşmek.", ""),
    "wordsc1gode.js|zugeflüstert": ("zuflüstern", "verb", "to whisper to someone. - kulağına fısıldamak.", ""),
    "wordsc1gode.js|zugelaufen": ("zulaufen", "verb", "to run towards; (of an animal) to stray to someone. - koşarak yaklaşmak; (hayvan) gelip sığınmak.", ""),
    "wordsc1gode.js|zugestanden": ("zustehen", "verb", "to be due to someone, to be someone's right. - hakkı olmak.", ""),
    "wordsc1gode.js|zugeworfen": ("zuwerfen", "verb", "to throw to someone; to slam shut. - atmak, fırlatmak; çarparak kapatmak.", ""),
    "wordsc1gode.js|zurechtgelegt": ("zurechtlegen", "verb", "to lay out ready; to work out in advance. - hazırlayıp koymak; önceden kurgulamak.",
                                     "Er hatte sich seine Antwort schon zurechtgelegt. - Cevabını çoktan hazırlamıştı."),
    "wordsc1gode.js|zurückgefallen": ("zurückfallen", "verb", "to fall back, to lag behind. - geri kalmak, gerilemek.", ""),
    "wordsc1gode.js|zusammengelegt": ("zusammenlegen", "verb", "to fold up; to merge; to pool money. - katlamak; birleştirmek; para toplamak.", ""),
    "wordsc1gode.js|zusammengepackt": ("zusammenpacken", "verb", "to pack up. - toplayıp paketlemek.",
                                       "Nach dem Markt haben wir alles zusammengepackt. - Pazardan sonra her şeyi toplayıp paketledik."),
    "wordsc1gode.js|zusammengepasst": ("zusammenpassen", "verb", "to go together, to match. - birbirine uymak, yakışmak.",
                                       "Die beiden haben von Anfang an gut zusammengepasst. - İkisi baştan beri birbirine iyi uydu."),

    # ===== wordsc2gode.js
    "wordsc2gode.js|Abkommen": ("Abkommen", "noun", "agreement, treaty. - anlaşma, antlaşma.", ""),
    "wordsc2gode.js|Aufsehen": ("Aufsehen", "noun", "stir, sensation, commotion. - sansasyon, dikkat çekme, gürültü.", ""),
    "wordsc2gode.js|Bedenken": ("Bedenken", "noun", "misgivings, reservations, concerns. - çekince, kaygı, endişe.", ""),
    "wordsc2gode.js|Bergsteigen": ("Bergsteigen", "noun", "mountaineering, mountain climbing. - dağcılık, dağa tırmanma.", ""),
    "wordsc2gode.js|Gefolgsleute": ("Gefolgsmann", "noun", "follower, retainer, henchman. - maiyet adamı, yandaş.",
                                    "Er war ein treuer Gefolgsmann des Königs. - Kralın sadık bir adamıydı."),
    "wordsc2gode.js|Gewissensbisse": ("Gewissensbiss", "noun", "pang of conscience, remorse. - vicdan azabı.",
                                      "Ihn plagte ein schlimmer Gewissensbiss. - Onu kötü bir vicdan azabı kemiriyordu."),
    "wordsc2gode.js|Glucksen": ("glucksen", "verb", "to chuckle; to gurgle. - kıkırdamak; lıkırdamak.",
                                "Das Wasser hörte man im Rohr glucksen. - Suyun boruda lıkırdadığı duyuluyordu."),
    "wordsc2gode.js|Grauen": ("Grauen", "noun", "horror, dread. - dehşet, korku.", ""),
    "wordsc2gode.js|Großbuchstaben": ("Großbuchstabe", "noun", "capital letter, upper-case letter. - büyük harf.", ""),
    "wordsc2gode.js|Handgreiflichkeiten": ("Handgreiflichkeit", "noun", "act of physical violence, scuffle. - fiziksel şiddet, arbede.",
                                           "Der Streit endete in einer Handgreiflichkeit. - Tartışma bir arbedeyle sona erdi."),
    "wordsc2gode.js|Hautschuppen": ("Hautschuppe", "noun", "flake of skin, dander. - deri pulcuğu, kepek.",
                                    "Eine winzige Hautschuppe blieb am Ärmel haften. - Kolda küçücük bir deri pulcuğu kaldı."),
    "wordsc2gode.js|Heben": ("heben", "verb", "to lift, to raise. - kaldırmak, yükseltmek.", ""),
    "wordsc2gode.js|Intimitäten": ("Intimität", "noun", "intimacy, closeness. - mahremiyet, yakınlık.",
                                   "Zwischen ihnen entstand eine große Intimität. - Aralarında büyük bir yakınlık oluştu."),
    "wordsc2gode.js|Schlafengehen": ("Schlafengehen", "noun", "going to bed, bedtime. - yatma, uyumaya gitme.", ""),
    "wordsc2gode.js|Vernickeln": ("Vernickeln", "noun", "nickel-plating. - nikel kaplama.",
                                  "Das Vernickeln schützt das Metall vor Rost. - Nikel kaplama, metali pastan korur."),
    "wordsc2gode.js|abbildend": ("abbildend", "adjective", "depicting, representational; mapping. - betimleyen, tasvir eden; eşleyen.",
                                 "Die Grafik ist rein abbildend, nicht deutend. - Grafik yorum katmaz, yalnızca betimler."),
    "wordsc2gode.js|abgemüht": ("abmühen", "verb", "to struggle, to toil away. - didinmek, uğraşıp durmak.", ""),
    "wordsc2gode.js|adstringierend": ("adstringierend", "adjective", "astringent. - büzücü, kekremsi.",
                                      "Der Tee schmeckt leicht adstringierend. - Çayın tadı hafif kekremsidir."),
    "wordsc2gode.js|aktivierend": ("aktivierend", "adjective", "activating, stimulating. - etkinleştirici, harekete geçirici.",
                                   "Der Kurs setzt auf aktivierende Lernmethoden. - Kurs, harekete geçirici öğrenme yöntemlerine dayanıyor."),
    "wordsc2gode.js|alternierend": ("alternierend", "adjective", "alternating. - dönüşümlü, almaşık.", ""),
    "wordsc2gode.js|angebellt": ("anbellen", "verb", "to bark at. - havlamak, üstüne havlamak.", ""),
    "wordsc2gode.js|angefeindet": ("anfeinden", "verb", "to be hostile towards, to attack. - düşmanlık etmek, hasım olmak.", ""),
    "wordsc2gode.js|angefixt": ("anfixen", "verb", "to get someone hooked on something. - birini alıştırmak, bağımlı hâle getirmek.",
                                "Ein Freund hat ihn mit dem Spiel angefixt. - Bir arkadaşı onu bu oyuna alıştırdı."),
    "wordsc2gode.js|angeworfen": ("anwerfen", "verb", "to start up an engine. - (motoru) çalıştırmak.",
                                  "Er hat den Motor angeworfen. - Motoru çalıştırdı."),
    "wordsc2gode.js|angezählt": ("anzählen", "verb", "to count out (boxing); to leave reeling. - (boksta) saymak; sarsmak.", ""),
    "wordsc2gode.js|angreifend": ("angreifend", "adjective", "attacking, offensive. - saldıran, hücum eden.",
                                  "Die angreifende Mannschaft war deutlich stärker. - Hücum eden takım açıkça daha güçlüydü."),
    "wordsc2gode.js|animierend": ("animierend", "adjective", "encouraging, stimulating, animating. - teşvik edici, canlandırıcı.",
                                  "Die Musik hatte eine animierende Wirkung. - Müziğin canlandırıcı bir etkisi vardı."),
    "wordsc2gode.js|antizipierend": ("antizipierend", "adjective", "anticipatory, anticipating. - önceden sezen, öngörücü.",
                                     "Sein antizipierendes Spiel machte den Unterschied. - Öngörülü oyunu farkı yarattı."),
    "wordsc2gode.js|aufgespielt": ("aufspielen", "verb", "to strike up music; to show off; to load software onto. - çalmaya başlamak; hava atmak; (yazılım) yüklemek.",
                                   "Die Kapelle hat zum Tanz aufgespielt. - Orkestra dans için çalmaya başladı."),
    "wordsc2gode.js|ausbrechend": ("ausbrechend", "adjective", "erupting, breaking out. - patlak veren, püsküren.",
                                   "Der ausbrechende Vulkan verdunkelte den Himmel. - Püsküren yanardağ göğü kararttı."),
    "wordsc2gode.js|ausgeblieben": ("ausbleiben", "verb", "to fail to appear, to not happen. - gelmemek, gerçekleşmemek.", ""),
    "wordsc2gode.js|ausgepustet": ("auspusten", "verb", "to blow out. - üfleyerek söndürmek.", ""),
    "wordsc2gode.js|ausgleichend": ("ausgleichend", "adjective", "balancing, compensating, conciliatory. - dengeleyici, telafi edici, uzlaştırıcı.", ""),
    "wordsc2gode.js|auswählend": ("auswählend", "adjective", "selecting, selective. - seçen, seçici.",
                                  "Er ging streng auswählend vor. - Titiz bir seçicilikle davrandı."),
    "wordsc2gode.js|bereitgelegt": ("bereitlegen", "verb", "to lay out ready, to put out in readiness. - hazır koymak, hazırlayıp bırakmak.",
                                    "Sie hat die Kleidung für morgen bereitgelegt. - Yarınki kıyafetleri hazır koydu."),
    "wordsc2gode.js|diffundiert": ("diffundiert", "adjective", "diffused, spread out evenly. - yayılmış, difüze olmuş.",
                                   "Das Gas ist gleichmäßig im Raum diffundiert. - Gaz odaya eşit biçimde yayıldı."),
    "wordsc2gode.js|durchgevögelt": ("durchvögeln", "verb", "(vulgar slang) to have sex with someone. - (kaba argo) biriyle yatmak.",
                                     "Das Wort ist derb und gehört nicht in die Schriftsprache. - Bu sözcük kabadır ve yazı diline uygun değildir."),
    "wordsc2gode.js|eingelenkt": ("einlenken", "verb", "to give in, to relent, to back down. - yumuşamak, geri adım atmak.", ""),
    "wordsc2gode.js|eingeschossen": ("einschießen", "verb", "to zero in a rifle; to pump in money. - (silahı) ayarlamak; (para) aktarmak.",
                                     "Das Gewehr wurde auf hundert Meter eingeschossen. - Tüfek yüz metreye göre ayarlandı."),
    "wordsc2gode.js|einverleibt": ("einverleiben", "verb", "to annex, to incorporate; to devour. - ilhak etmek, katmak; silip süpürmek.",
                                   "Das Reich hat die Provinz einverleibt. - İmparatorluk vilayeti ilhak etti."),
    "wordsc2gode.js|entwöhnt": ("entwöhnen", "verb", "to wean; to break someone of a habit. - sütten kesmek; alışkanlıktan kurtarmak.", ""),
    "wordsc2gode.js|geemailt": ("emailen", "verb", "to email. - e-posta göndermek.", ""),
    "wordsc2gode.js|gefakt": ("faken", "verb", "to fake, to counterfeit. - sahtesini yapmak, taklit etmek.",
                              "Die Unterschrift war eindeutig gefakt. - İmza kesinlikle sahteydi."),
    "wordsc2gode.js|geschlampt": ("schlampen", "verb", "to be sloppy, to do a shoddy job. - baştan savma iş yapmak.", ""),
    "wordsc2gode.js|gezollt": ("zollen", "verb", "to pay (respect, tribute). - (saygı, takdir) göstermek.",
                               "Man hat ihm großen Respekt gezollt. - Ona büyük saygı gösterildi."),
    "wordsc2gode.js|heimgegangen": ("heimgehen", "verb", "to go home; to pass away. - eve gitmek; vefat etmek.", ""),
    "wordsc2gode.js|herabgelassen": ("herablassen", "verb", "to lower down; to condescend. - aşağı indirmek; tenezzül etmek.", ""),
    "wordsc2gode.js|laminiert": ("laminieren", "verb", "to laminate. - laminasyon yapmak, plastikle kaplamak.", ""),
    "wordsc2gode.js|umgeschlagen": ("umschlagen", "verb", "to change abruptly; to transship. - (hava, ruh hâli) birden dönmek; aktarmak.", ""),
    "wordsc2gode.js|umrandet": ("umranden", "verb", "to border, to edge, to rim. - çevrelemek, kenarını çerçevelemek.", ""),
    "wordsc2gode.js|vergilbt": ("vergilben", "verb", "to yellow, to go yellow with age. - sararmak.", ""),
    "wordsc2gode.js|verkalkuliert": ("verkalkulieren", "verb", "to miscalculate, to get one's sums wrong. - hesabı yanlış yapmak, yanılmak.", ""),
    "wordsc2gode.js|verlacht": ("verlachen", "verb", "to laugh at, to deride. - alay etmek, gülüp geçmek.", ""),
    "wordsc2gode.js|verletzt": ("verletzt", "adjective", "injured, hurt; offended. - yaralı; incinmiş, gücenmiş.", ""),
    "wordsc2gode.js|versiebt": ("versieben", "verb", "to botch, to mess up. - eline yüzüne bulaştırmak, batırmak.",
                                "Er hat die Prüfung völlig versiebt. - Sınavı tamamen batırdı."),
    "wordsc2gode.js|verwandt": ("verwandt", "adjective", "related, akin. - akraba, ilgili.", ""),
    "wordsc2gode.js|vorangegangen": ("vorangehen", "verb", "to go ahead, to precede. - önden gitmek, önce gelmek.", ""),
    "wordsc2gode.js|vorgelassen": ("vorlassen", "verb", "to let someone go first, to admit someone. - önce geçirmek, huzura kabul etmek.", ""),
    "wordsc2gode.js|vorgewagt": ("vorwagen", "verb", "to venture forward, to dare to come forward. - öne çıkmaya cesaret etmek.",
                                 "Niemand hat sich in die Höhle vorgewagt. - Kimse mağaraya girmeye cesaret edemedi."),
    "wordsc2gode.js|weggedrückt": ("wegdrücken", "verb", "to push away; to dismiss a call. - itip uzaklaştırmak; (aramayı) reddetmek.",
                                   "Er hat den Anruf einfach weggedrückt. - Aramayı öylece reddetti."),
    "wordsc2gode.js|wiedergekehrt": ("wiederkehren", "verb", "to return, to recur. - geri dönmek, yinelenmek.",
                                     "Die Schmerzen sind nach Wochen wiedergekehrt. - Ağrılar haftalar sonra geri döndü."),
    "wordsc2gode.js|wiedergewinnend": ("wiedergewinnend", "adjective", "regaining, recovering. - yeniden kazanan, geri elde eden.",
                                       "Ein die Kräfte wiedergewinnender Schlaf tat ihm gut. - Gücünü geri kazandıran bir uyku ona iyi geldi."),
    "wordsc2gode.js|zugekehrt": ("zukehren", "verb", "to turn towards, to turn something to someone. - (bir yöne) çevirmek, dönmek.", ""),
    "wordsc2gode.js|zugerufen": ("zurufen", "verb", "to call out to someone. - seslenmek, bağırarak söylemek.",
                                 "Er hat mir vom anderen Ufer etwas zugerufen. - Karşı kıyıdan bana bir şeyler seslendi."),
    "wordsc2gode.js|zugeschoben": ("zuschieben", "verb", "to push towards; to shift blame onto. - itip yaklaştırmak; (suçu) yıkmak.", ""),
    "wordsc2gode.js|zugewachsen": ("zuwachsen", "verb", "to become overgrown; to heal over. - otlarla kaplanmak; kapanmak.", ""),
    "wordsc2gode.js|zurückgelehnt": ("zurücklehnen", "verb", "to lean back. - arkaya yaslanmak.", ""),
    "wordsc2gode.js|zurückgewichen": ("zurückweichen", "verb", "to back away, to recoil. - geri çekilmek, gerilemek.", ""),
    "wordsc2gode.js|zusammengeblieben": ("zusammenbleiben", "verb", "to stay together. - birlikte kalmak.", ""),
    "wordsc2gode.js|zusammengezuckt": ("zusammenzucken", "verb", "to flinch, to start. - irkilmek, sıçramak.", ""),
    "wordsc2gode.js|ätzend": ("ätzend", "adjective", "caustic, corrosive; (slang) awful. - yakıcı, aşındırıcı; (argo) berbat.", ""),
    "wordsc2gode.js|äußerster": ("äußerster", "adjective", "outermost, utmost, extreme. - en dıştaki, azami, aşırı.",
                                 "Das ist von äußerster Wichtigkeit. - Bu, azami derecede önemlidir."),
    "wordsc2gode.js|überdimensioniert": ("überdimensioniert", "adjective", "oversized, larger than needed. - aşırı büyük, gereğinden büyük.",
                                         "Die Anlage ist für den Bedarf überdimensioniert. - Tesis, ihtiyaca göre gereğinden büyük."),
    "wordsc2gode.js|übereingekommen": ("übereinkommen", "verb", "to agree, to come to an agreement. - anlaşmaya varmak, mutabık kalmak.", ""),
    "wordsc2gode.js|überhäuft": ("überhäuft", "adjective", "swamped, inundated, showered with. - boğulmuş, yağmuruna tutulmuş.", ""),
    "wordsc2gode.js|überschäumend": ("überschäumend", "adjective", "effervescent, exuberant, bubbling over. - coşkun, taşkın.", ""),
    "wordsc2gode.js|überströmt": ("überströmen", "verb", "to flood, to overflow, to inundate. - taşmak, sel gibi kaplamak.", ""),
    "wordsc2gode.js|überwuchert": ("überwuchern", "verb", "to overgrow, to smother with growth. - sarıp kaplamak, istila etmek.", ""),
}
