# -*- coding: utf-8 -*-
"""Curated replacement definitions for data/synantde.js entries whose upstream
Wiktionary gloss was only a 'form-of' stub ("Partizip Perfekt von X",
"Gerundium von X", "Plural von X", "Flexion von X").

Consumed by scripts/fix_synant_formof.py --content.

    CONTENT["<current headword>"] = (
        new_word,        # "" = keep the existing headword
        definition_de,   # German gloss   -- MUST NOT contain ';'
        definition_tr,   # Turkish gloss  -- MUST NOT contain ';'
        example_de,      # "" = keep the existing example pair
        example_tr,
    )

The stored field format is "<native>;<Turkish>" with exactly ONE semicolon as
the boundary, so semicolons inside a half are forbidden -- use commas.
"""

CONTENT = {
    # ===== nominalised infinitives (Gerundium von X) and plurals ==========
    "Schlafengehen": ("", "das Zubettgehen, der Beginn der Nachtruhe", "yatma, uykuya gitme", "", ""),
    "Abfragen": ("", "das mündliche Abprüfen von Wissen, auch das Abrufen von Daten", "sözlü yoklama, sorgulama", "", ""),
    "Durchbrennen": ("", "heimliches Weglaufen, die Flucht", "kaçış, firar", "", ""),
    "Abheften": ("", "das Einordnen von Papieren in einen Ordner", "evrakları dosyalama", "", ""),
    "Abkommen": ("", "schriftliche Vereinbarung zwischen zwei Parteien, Vertrag", "anlaşma, sözleşme", "", ""),
    "Abnehmen": ("", "Rückgang und Verringerung, auch der Verlust an Gewicht", "azalma, kilo verme", "", ""),
    "Abschneiden": ("", "das Trennen mit Schere oder Messer, auch das Ergebnis bei einem Vergleich", "kesme, ayırma", "", ""),
    "Abschwören": ("", "die feierliche Lossagung von einer Überzeugung", "yeminle vazgeçme, tövbe etme", "", ""),
    "Absenden": ("", "das Wegschicken einer Nachricht oder Sendung", "gönderme, yollama", "", ""),
    "Abstimmen": ("", "die Stimmabgabe bei einer Wahl, auch das gegenseitige Anpassen", "oylama, uyumlaştırma", "", ""),
    "Adressieren": ("", "das Versehen einer Sendung mit einer Anschrift", "adresleme", "", ""),
    "Allüren": ("Allüre", "auffälliges und überhebliches Gehabe", "hava, caka, tavır", "", ""),
    "Anheften": ("", "das Befestigen mit Nadel, Klammer oder Klebstoff", "iliştirme, tutturma", "", ""),
    "Anschreiben": ("", "kurzes Begleitschreiben zu einer Sendung", "ön yazı, kapak yazısı", "", ""),
    "Ansehen": ("", "hohe Wertschätzung, guter Ruf in der Öffentlichkeit", "itibar, saygınlık", "", ""),
    "Ansiedeln": ("", "das Sesshaftwerden an einem neuen Ort", "yerleşme, iskân", "", ""),
    "Aufstellen": ("", "das Hinstellen oder Errichten, auch das Zusammenstellen einer Liste", "kurma, dikme", "", ""),
    "Aufsehen": ("", "großes öffentliches Interesse, Sensation", "sansasyon, büyük ilgi", "", ""),
    "Auseinandergehen": ("", "das Sichtrennen, das Auseinanderdriften von Meinungen", "ayrılma, uzaklaşma", "", ""),
    "Aushalten": ("", "das geduldige Ertragen einer Belastung", "dayanma, katlanma", "", ""),
    "Aussetzen": ("", "die zeitweilige Unterbrechung, auch das schutzlose Preisgeben", "ara verme, terk etme", "", ""),
    "Bauchschmerzen": ("Bauchschmerz", "Schmerz im Bauchraum", "karın ağrısı", "", ""),
    "Bedenken": ("", "Zweifel oder Einwand gegen ein Vorhaben", "çekince, endişe", "", ""),
    "Begießen": ("", "das Übergießen mit Flüssigkeit", "sulama, üzerine dökme", "", ""),
    "Begreifen": ("", "die Fähigkeit, einen Sachverhalt geistig zu erfassen", "kavrayış, anlama", "", ""),
    "Beiwohnen": ("", "die Teilnahme als anwesender Zuschauer", "hazır bulunma, katılım", "", ""),
    "Beißen": ("", "das Zupacken mit den Zähnen", "ısırma", "", ""),
    "Bekannten": ("Bekannte", "Person, die man kennt, ohne eng befreundet zu sein", "tanıdık", "", ""),
    "Bellen": ("", "der laute Ruf eines Hundes", "havlama", "", ""),
    "Bergsteigen": ("", "das Besteigen von Bergen als Sport", "dağcılık", "", ""),
    "Beugen": ("", "das Krümmen oder Neigen des Körpers", "eğilme, bükme", "", ""),
    "Chancen": ("Chance", "günstige Gelegenheit, Aussicht auf Erfolg", "şans, fırsat", "", ""),
    "Daten": ("", "Angaben und Informationen, die gesammelt und ausgewertet werden", "veri, veriler", "", ""),
    "Eindringen": ("", "das gewaltsame Hineingelangen in einen Bereich", "içeri girme, sızma", "", ""),
    "Eingehen": ("", "das Kleinerwerden von Stoff beim Waschen, auch das Zugrundegehen", "çekme, büzüşme", "", ""),
    "Eingreifen": ("", "das aktive Einschreiten in einen laufenden Vorgang", "müdahale", "", ""),
    "Einkommen": ("", "regelmäßige Einnahmen aus Arbeit oder Vermögen", "gelir", "", ""),
    "Erbrechen": ("", "das Entleeren des Mageninhalts durch den Mund", "kusma", "", ""),
    "Entgegenkommen": ("", "freundliche Bereitschaft, jemandem auf halbem Weg zu helfen", "yardımseverlik, hoşgörü", "", ""),
    "Entsetzen": ("", "heftiger Schrecken, tiefes Grauen", "dehşet, korku", "", ""),
    "Entzücken": ("", "große Freude, helles Vergnügen", "büyük keyif, hayranlık", "", ""),
    "Ernten": ("", "das Einbringen der reifen Feldfrüchte", "hasat etme, toplama", "", ""),
    "Erstaunen": ("", "Verblüffung über etwas Unerwartetes", "şaşkınlık, hayret", "", ""),
    "Essen": ("", "Speise und Mahlzeit, alles was gegessen wird", "yemek", "", ""),
    "Finanzen": ("", "die Geldmittel einer Person, eines Unternehmens oder eines Staates", "mali durum, maliye", "", ""),
    "Flattern": ("", "unruhiges Hin-und-her-Schwingen, etwa von Flügeln oder Fahnen", "çırpınma, titreşim", "", ""),
    "Flusen": ("Fluse", "kleines Fussel- oder Staubfäserchen aus Textilien", "tüycük, hav", "", ""),
    "Flüstern": ("", "das sehr leise Sprechen ohne Stimme", "fısıltı", "", ""),
    "Funkeln": ("", "das helle, blitzende Aufleuchten von Licht", "parıltı, ışıldama", "", ""),
    "Gefolgsleute": ("", "treue Anhänger und Untergebene eines Anführers", "maiyet, taraftarlar", "", ""),
    "Gewissensbisse": ("Gewissensbiss", "quälendes Schuldgefühl nach einer Tat", "vicdan azabı", "", ""),
    "Glucksen": ("", "leises, kicherndes Lachen oder gluckerndes Geräusch", "kıkırdama, lıkırtı", "", ""),
    "Grauen": ("", "tiefes Entsetzen, kalter Schauder", "dehşet, ürperti", "", ""),
    "Großbuchstaben": ("Großbuchstabe", "großer Buchstabe am Wort- oder Satzanfang", "büyük harf", "", ""),
    "Güter": ("Gut", "Ware oder Besitz von Wert, auch großer Landbesitz", "mal, mülk", "", ""),
    "Handgreiflichkeiten": ("Handgreiflichkeit", "tätlicher Angriff im Streit", "fiili saldırı, sataşma", "", ""),
    "Hautschuppen": ("Hautschuppe", "kleines abgestorbenes Hautplättchen", "deri pulu, kepek", "", ""),
    "Heben": ("", "das Hochbewegen einer Last", "kaldırma", "", ""),
    "Hülsenfrüchte": ("Hülsenfrucht", "Pflanze mit Samen in einer Hülse, etwa Bohne oder Linse", "baklagil", "", ""),
    "Intimitäten": ("Intimität", "vertrauliche Nähe zwischen zwei Menschen", "mahremiyet, samimiyet", "", ""),
    "Knurren": ("", "dumpfer Drohlaut eines Tieres, auch das Rumoren des Magens", "hırlama, guruldama", "", ""),
    "Kräfte": ("Kraft", "körperliche oder geistige Stärke", "güç, kuvvet", "", ""),
    "Schuhe": ("Schuh", "festes Kleidungsstück für den Fuß", "ayakkabı", "", ""),
    "Messen": ("", "das Bestimmen einer Größe mit einem Maßstab", "ölçme", "", ""),
    "Millionen": ("Million", "Zahl von tausend mal tausend", "milyon", "", ""),
    "Misstrauen": ("", "Mangel an Vertrauen, wacher Argwohn", "güvensizlik, kuşku", "", ""),
    "Nachkommen": ("Nachkomme", "Kind oder späterer Abkömmling einer Person", "torun, soydan gelen", "", ""),
    "Nachäffen": ("", "das spöttische Nachmachen von Worten und Gesten", "alaycı taklit", "", ""),
    "Nudeln": ("Nudel", "Teigware aus Mehl, Wasser und oft Ei", "makarna, erişte", "", ""),
    "Rütteln": ("", "kräftiges Hin-und-her-Schütteln", "sarsma, silkeleme", "", ""),
    "Scheren": ("", "das Kurzschneiden von Wolle oder Haar", "kırkma, kesme", "", ""),
    "Schleifen": ("", "das Glätten oder Schärfen einer Oberfläche", "bileme, zımparalama", "", ""),
    "Stichpunkte": ("Stichpunkt", "kurzes Stichwort in einer Notiz oder Gliederung", "madde başı, not", "", ""),
    "Strümpfe": ("Strumpf", "Kleidungsstück aus Gestrick für Fuß und Bein", "çorap", "", ""),
    "Vergolden": ("", "das Überziehen einer Oberfläche mit einer Goldschicht", "altın kaplama", "", ""),
    "Vernickeln": ("", "das Überziehen einer Oberfläche mit einer Nickelschicht", "nikel kaplama", "", ""),
    "Verschrotten": ("", "das Zerlegen von Altmetall zur Wiederverwertung", "hurdaya ayırma", "", ""),
    "Versilbern": ("", "das Überziehen einer Oberfläche mit einer Silberschicht", "gümüş kaplama", "", ""),
    "Vertrauen": ("", "festes Zutrauen in die Zuverlässigkeit eines anderen", "güven", "", ""),
    "Vorgehen": ("", "die geplante Art und Weise zu handeln", "yöntem, hareket tarzı", "", ""),

    # ===== determiners, pronouns and adjective base forms =================
    "alle": ("", "jeder Einzelne einer Gesamtheit, sämtliche", "hepsi, tümü", "", ""),
    "andere": ("", "nicht dieselbe Person oder Sache, weitere", "diğer, başka", "", ""),
    "einige": ("", "eine unbestimmte, eher kleine Anzahl", "bazı, birkaç", "", ""),
    "das": ("", "bestimmter Artikel im Neutrum, auch hinweisendes Fürwort", "nötr belirli tanımlık, bu", "", ""),
    "diese": ("", "hinweisendes Fürwort für etwas räumlich oder zeitlich Nahes", "bu, bunlar", "", ""),
    "schnellen": ("", "sich ruckartig und sehr schnell bewegen, in die Höhe schießen", "fırlamak, hızla yükselmek",
                  "Die Preise schnellen in die Höhe.", "Fiyatlar hızla yükseliyor."),
    "alternative": ("alternativ", "eine andere Möglichkeit bietend, andersartig", "alternatif, seçenek sunan",
                    "Wir suchen nach alternativen Lösungen.", "Alternatif çözümler arıyoruz."),
    "diverse": ("divers", "verschieden, von unterschiedlicher Art", "çeşitli, muhtelif", "", ""),
    "innere": ("inner", "im Inneren liegend, nach innen gerichtet", "iç, içteki",
               "Er hörte auf seine innere Stimme.", "İç sesini dinledi."),
    "letzter": ("letzt", "am Ende einer Reihe stehend, zuletzt kommend", "son, sonuncu", "", ""),

    # ===== participial adjectives =========================================
    "abbildend": ("", "etwas bildlich darstellend, stellvertretend wiedergebend", "temsil eden, betimleyen", "", ""),
    "abfallend": ("", "nach unten geneigt, allmählich geringer werdend", "aşağı eğimli, azalan", "", ""),
    "abgearbeitet": ("", "von harter Arbeit völlig erschöpft", "çalışmaktan yorgun düşmüş", "", ""),
    "abgedroschen": ("", "durch häufigen Gebrauch abgenutzt und banal geworden", "basmakalıp, klişe", "", ""),
    "abgehoben": ("", "der Wirklichkeit entrückt, überheblich wirkend", "gerçeklikten kopuk, ukala", "", ""),
    "abgegriffen": ("", "durch häufiges Anfassen sichtbar abgenutzt", "elden ele geçmekten yıpranmış", "", ""),
    "abgehackt": ("", "stockend und ohne fließenden Zusammenhang", "kesik kesik", "", ""),
    "abgehärtet": ("", "widerstandsfähig gegen Kälte und Strapazen", "sertleşmiş, dayanıklı", "", ""),
    "abgekapselt": ("", "von der Umwelt abgeschlossen und isoliert", "kapanmış, yalıtılmış", "", ""),
    "abgeklungen": ("", "allmählich schwächer geworden und verschwunden", "yatışmış, geçmiş", "", ""),
    "abgeklärt": ("", "ruhig und gelassen aus Lebenserfahrung", "olgun, sakin", "", ""),
    "abgelegen": ("", "weit entfernt von Siedlungen und Verkehrswegen", "ücra, uzak", "", ""),
    "abgeleitet": ("", "aus etwas anderem folgerichtig hergeleitet", "türetilmiş, çıkarsanmış", "", ""),
    "abgemacht": ("", "vorher fest vereinbart", "kararlaştırılmış, anlaşılmış", "", ""),
    "abgemagert": ("", "stark an Gewicht verloren habend", "zayıflamış, bir deri bir kemik", "", ""),
    "abgemildert": ("", "in seiner Wirkung abgeschwächt", "hafifletilmiş", "", ""),
    "abgenutzt": ("", "durch langen Gebrauch verschlissen", "yıpranmış, eskimiş", "", ""),
    "abgepackt": ("", "fertig in Packungen abgefüllt", "paketlenmiş", "", ""),
    "abgerissen": ("", "zerlumpt und schäbig, auch niedergerissen", "yırtık pırtık, yıkılmış", "", ""),
    "abgerundet": ("", "ohne scharfe Kanten, in sich stimmig und harmonisch", "yuvarlatılmış, uyumlu", "", ""),
    "abgeschieden": ("", "einsam und zurückgezogen gelegen", "tenha, inzivada", "", ""),
    "abgeschlossen": ("", "fest verschlossen, auch vollständig beendet", "kilitli, tamamlanmış", "", ""),
    "abgeschrägt": ("", "mit schräg verlaufender Kante versehen", "eğimli kesilmiş", "", ""),
    "ausgenommen": ("", "von einer Regel nicht betroffen", "hariç, dışında", "", ""),
    "abgesondert": ("", "von allem anderen getrennt gehalten", "ayrılmış, tecrit edilmiş", "", ""),
    "abgestanden": ("", "schal geworden und nicht mehr frisch", "bayat, tadı kaçmış", "", ""),
    "abgestimmt": ("", "sorgfältig aufeinander angepasst", "uyumlu hale getirilmiş", "", ""),
    "abgewirtschaftet": ("", "durch schlechte Führung völlig heruntergekommen", "batmış, harap olmuş", "", ""),
    "ablehnend": ("", "eine Bitte oder Meinung zurückweisend", "reddedici, olumsuz", "", ""),
    "abschließend": ("", "am Ende stehend und zusammenfassend", "son olarak, kapanış niteliğinde", "", ""),
    "abwehrend": ("", "einen Angriff zurückweisend, defensiv", "savunmacı, savuşturucu", "", ""),
    "abweichend": ("", "vom Üblichen oder Erwarteten verschieden", "farklı, sapan", "", ""),
    "abwertend": ("", "herabsetzend und geringschätzig", "aşağılayıcı", "", ""),
    "adstringierend": ("", "das Gewebe zusammenziehend", "büzücü", "", ""),
    "affektiert": ("", "unnatürlich geziert im Auftreten", "yapmacık, özentili", "", ""),
    "aktivierend": ("", "anregend und in Schwung bringend", "harekete geçirici, canlandırıcı", "", ""),
    "alkoholisiert": ("", "unter dem Einfluss von Alkohol stehend", "alkollü, sarhoş", "", ""),
    "aufgebraucht": ("", "vollständig verbraucht, nichts mehr übrig", "tükenmiş", "", ""),
    "alliiert": ("", "verbündet, in einem Bündnis stehend", "müttefik", "", ""),
    "alternierend": ("", "regelmäßig abwechselnd", "dönüşümlü, almaşık", "", ""),
    "andauernd": ("", "ohne Unterbrechung fortbestehend", "sürekli, devamlı", "", ""),
    "anerkannt": ("", "allgemein geschätzt und akzeptiert", "tanınmış, kabul görmüş", "", ""),
    "angebracht": ("", "der Situation entsprechend und sinnvoll", "yerinde, uygun", "", ""),
    "angebrochen": ("", "gerade erst begonnen oder geöffnet", "başlamış, açılmış", "", ""),
    "angefochten": ("", "in seiner Gültigkeit bestritten", "itiraz edilmiş, tartışmalı", "", ""),
    "angegliedert": ("", "organisatorisch an eine größere Einheit angeschlossen", "bağlanmış, iliştirilmiş", "", ""),
    "angemessen": ("", "dem Zweck und dem rechten Maß entsprechend", "uygun, makul", "", ""),
    "angenommen": ("", "als wahr unterstellt, auch angenommen und akzeptiert", "varsayılan, kabul edilmiş", "", ""),
    "angepasst": ("", "auf die jeweiligen Umstände abgestimmt", "uyarlanmış", "", ""),
    "angeschlagen": ("", "leicht beschädigt oder gesundheitlich geschwächt", "hasarlı, zayıf düşmüş", "", ""),
    "angeschlossen": ("", "verbunden, an ein Netz oder eine Gruppe gekoppelt", "bağlı", "", ""),
    "angeschwollen": ("", "dick geworden, geschwollen", "şişmiş", "", ""),
    "angesehen": ("", "hohes Ansehen genießend", "itibarlı, saygın", "", ""),
    "angespannt": ("", "unter starker Spannung oder Nervosität stehend", "gergin", "", ""),
    "angestellt": ("", "in einem festen Arbeitsverhältnis beschäftigt", "çalışan, ücretli", "", ""),
    "angreifend": ("", "offensiv vorgehend", "saldırgan, hücum eden", "", ""),
    "angrenzend": ("", "unmittelbar daneben liegend", "bitişik, komşu", "", ""),
    "anheimelnd": ("", "behaglich und vertraut wirkend", "iç açıcı, sıcak", "", ""),
    "animierend": ("", "zum Mitmachen anregend", "teşvik edici", "", ""),
    "anklagend": ("", "einen deutlichen Vorwurf erhebend", "suçlayıcı", "", ""),
    "annähernd": ("", "nicht ganz genau, ungefähr", "yaklaşık", "", ""),
    "anschließend": ("", "unmittelbar danach folgend", "ardından, sonrasında", "", ""),
    "ansprechend": ("", "angenehm wirkend und gefällig", "çekici, hoş", "", ""),
    "anstrengend": ("", "viel Kraft und Mühe erfordernd", "yorucu", "", ""),
    "antizipierend": ("", "künftige Entwicklungen vorwegnehmend", "öngörülü", "", ""),
    "einleuchtend": ("", "sofort verständlich und überzeugend", "mantıklı, ikna edici", "", ""),
    "aufbauend": ("", "förderlich und konstruktiv", "yapıcı", "", ""),
    "aufbrausend": ("", "schnell und heftig zornig werdend", "çabuk parlayan, öfkeli", "", ""),
    "aufgeblasen": ("", "überheblich und wichtigtuerisch", "kibirli, şişinmiş", "", ""),
    "aufgebracht": ("", "sehr verärgert und empört", "öfkeli, sinirlenmiş", "", ""),
    "aufgeklärt": ("", "vorurteilsfrei und von Vernunft geleitet", "aydınlanmış, önyargısız", "", ""),
    "aufgeregt": ("", "nervös und innerlich erregt", "heyecanlı, telaşlı", "", ""),
    "aufgeladen": ("", "mit Energie oder Last versehen", "yüklü, şarj edilmiş", "", ""),
    "aufgelöst": ("", "vor Aufregung außer Fassung, auch in Flüssigkeit gelöst", "allak bullak, çözünmüş", "", ""),
    "aufgeräumt": ("", "in Ordnung gebracht, auch guter Laune", "derli toplu, neşeli", "", ""),
    "aufgeschlossen": ("", "offen und interessiert für Neues", "açık fikirli", "", ""),
    "aufgeweckt": ("", "geistig wach und schnell begreifend", "zeki, uyanık", "", ""),
    "aufopfernd": ("", "sich selbstlos für andere einsetzend", "fedakâr", "", ""),
    "aufreizend": ("", "herausfordernd und provozierend", "kışkırtıcı, cilveli", "", ""),
    "gebraucht": ("", "schon benutzt und nicht mehr neu", "kullanılmış, ikinci el", "", ""),
    "ausbrechend": ("", "plötzlich und heftig hervorbrechend", "patlak veren", "", ""),
    "ausdauernd": ("", "beharrlich über lange Zeit durchhaltend", "dayanıklı, azimli", "", ""),
    "diffundiert": ("", "gleichmäßig verteilt und zerstreut", "yayılmış, dağılmış", "", ""),
    "auserkoren": ("", "für eine Aufgabe eigens ausgewählt", "seçilmiş", "", ""),
    "ausgebeutet": ("", "rücksichtslos ausgenutzt", "sömürülmüş", "", ""),
    "ausgebildet": ("", "fachlich geschult und qualifiziert", "eğitimli, yetişmiş", "", ""),
    "ausgedacht": ("", "frei erfunden, nicht wirklich geschehen", "uydurulmuş", "", ""),
    "ausgedehnt": ("", "weit ausgebreitet oder lange dauernd", "geniş, uzun süren", "", ""),
    "ausgefallen": ("", "ungewöhnlich und originell", "sıra dışı, özgün", "", ""),
    "ausgeführt": ("", "in die Tat umgesetzt", "uygulanmış, yerine getirilmiş", "", ""),
    "ausgeglichen": ("", "ruhig und innerlich im Gleichgewicht", "dengeli", "", ""),
    "ausgeklügelt": ("", "bis ins kleinste Detail durchdacht", "ince hesaplanmış", "", ""),
    "ausgelastet": ("", "voll beansprucht, ohne freie Kapazität", "tam kapasite çalışan", "", ""),
    "ausgemergelt": ("", "durch Entbehrung bis auf die Knochen abgezehrt", "bir deri bir kemik kalmış", "", ""),
    "ausgeprägt": ("", "deutlich und stark erkennbar", "belirgin", "", ""),
    "ausgerechnet": ("", "gerade dieser eine, oft unpassenderweise", "tam da, ille de", "", ""),
    "ausgereift": ("", "vollständig entwickelt und gut durchdacht", "olgunlaşmış", "", ""),
    "ausgeschlossen": ("", "gar nicht möglich, auch nicht zugelassen", "imkânsız, dışlanmış", "", ""),
    "ausgestoßen": ("", "aus der Gemeinschaft verbannt", "dışlanmış, kovulmuş", "", ""),
    "ausgewachsen": ("", "voll entwickelt und erwachsen", "yetişkin, tam büyümüş", "", ""),
    "ausgezeichnet": ("", "von hervorragender Qualität", "mükemmel, üstün", "", ""),
    "ausgleichend": ("", "Gegensätze abmildernd und versöhnend", "dengeleyici", "", ""),
    "ausreichend": ("", "gerade genug für den Zweck", "yeterli", "", ""),
    "ausverkauft": ("", "vollständig verkauft, kein Platz mehr frei", "tükenmiş, dolu", "", ""),
    "auswählend": ("", "gezielt aussuchend, selektiv", "seçici", "", ""),
    "bedacht": ("", "überlegt und vorsichtig handelnd", "ihtiyatlı, düşünceli", "", ""),
    "bedeckt": ("", "mit einer Schicht überzogen, auch bewölkt", "örtülü, bulutlu", "", ""),
    "bedeutend": ("", "wichtig und von großem Gewicht", "önemli, kayda değer", "", ""),
    "bedingt": ("", "nur unter Vorbehalt und mit Einschränkung geltend", "koşullu, kısmen", "", ""),
    "bedrückend": ("", "schwer auf dem Gemüt lastend", "iç karartıcı", "", ""),
    "bedrückt": ("", "traurig und niedergeschlagen", "üzgün, morali bozuk", "", ""),
    "beeinflussend": ("", "auf Meinung oder Verlauf einwirkend", "etkileyici, yönlendirici", "", ""),
    "beeinflusst": ("", "von etwas geprägt und gelenkt", "etkilenmiş", "", ""),
    "beflissen": ("", "eifrig um etwas bemüht", "gayretli, hevesli", "", ""),
    "befriedigt": ("", "in seinen Wünschen zufriedengestellt", "tatmin olmuş", "", ""),
    "befugt": ("", "mit einer Berechtigung ausgestattet", "yetkili", "", ""),
    "begabt": ("", "mit natürlichem Talent ausgestattet", "yetenekli", "", ""),
    "beginnend": ("", "gerade erst einsetzend", "başlangıç aşamasında", "", ""),
    "begleitend": ("", "gleichzeitig neben etwas herlaufend", "eşlik eden", "", ""),
    "beglückt": ("", "von großer Freude erfüllt", "mutlu, sevinçli", "", ""),
    "begrenzt": ("", "in Umfang oder Menge beschränkt", "sınırlı", "", ""),
    "begründend": ("", "einen Grund oder Beleg liefernd", "gerekçelendirici", "", ""),
    "beheimatet": ("", "irgendwo zu Hause und dort verbreitet", "yerleşik, yöreye özgü", "", ""),
    "beherrschend": ("", "alles bestimmend und dominierend", "baskın, hâkim", "", ""),
    "behindert": ("", "in seinen Möglichkeiten dauerhaft eingeschränkt", "engelli, kısıtlanmış", "", ""),
    "bekannt": ("", "vielen Menschen vertraut", "tanınmış, meşhur", "", ""),
    "belehrend": ("", "mit erhobenem Zeigefinger unterrichtend", "ders verir tarzda", "", ""),
    "beleidigend": ("", "die Ehre eines anderen verletzend", "hakaret edici", "", ""),
    "berauscht": ("", "von Rausch oder Begeisterung erfüllt", "sarhoş, kendinden geçmiş", "", ""),
    "berechtigt": ("", "rechtlich zulässig, auch sachlich begründet", "haklı, yetkili", "", ""),
    "beruhigend": ("", "Unruhe und Angst nehmend", "sakinleştirici, yatıştırıcı", "", ""),
    "beschreibend": ("", "Sachverhalte schildernd statt bewertend", "betimleyici", "", ""),
    "beschränkt": ("", "geistig eng, auch mengenmäßig begrenzt", "dar görüşlü, sınırlı", "", ""),
    "beschädigt": ("", "nicht mehr unversehrt", "hasarlı, bozuk", "", ""),
    "beschämend": ("", "Scham hervorrufend", "utandırıcı", "", ""),
    "beschützend": ("", "vor Gefahr bewahrend", "koruyucu", "", ""),
    "besonnen": ("", "ruhig und überlegt handelnd", "sağduyulu, sakin", "", ""),
    "bestehend": ("", "vorhanden und weiter fortdauernd", "mevcut, var olan", "", ""),
    "bestimmt": ("", "klar festgelegt, auch entschlossen im Auftreten", "belirli, kararlı", "", ""),
    "beurkundet": ("", "amtlich schriftlich bestätigt", "belgelenmiş", "", ""),
    "bewaldet": ("", "mit Wald bedeckt", "ormanlık", "", ""),
    "bewandert": ("", "auf einem Gebiet gut Bescheid wissend", "bilgili, ehil", "", ""),
    "bewiesen": ("", "zweifelsfrei nachgewiesen", "kanıtlanmış", "", ""),
    "bewährt": ("", "in der Praxis erprobt und zuverlässig", "denenmiş, güvenilir", "", ""),
    "beängstigend": ("", "Angst und Sorge auslösend", "ürkütücü, endişe verici", "", ""),
    "bindend": ("", "rechtlich verpflichtend", "bağlayıcı", "", ""),
    "blendend": ("", "grell leuchtend, auch hervorragend", "göz kamaştırıcı", "", ""),
    "dediziert": ("", "eigens für einen einzigen Zweck bestimmt", "özel olarak ayrılmış", "", ""),
    "demotivierend": ("", "Lust und Antrieb nehmend", "motivasyon kırıcı", "", ""),
    "gehäuft": ("", "vermehrt und in großer Zahl auftretend", "sık görülen, yığılmış", "", ""),
    "designiert": ("", "für ein Amt bereits vorgesehen", "aday gösterilmiş", "", ""),
    "distanziert": ("", "kühl und auf Abstand bedacht", "mesafeli", "", ""),
    "doppelt": ("", "zweimal vorhanden, in zweifacher Ausführung", "çift, iki kat", "", ""),
    "dringend": ("", "keinen Aufschub duldend", "acil", "", ""),
    "duftend": ("", "angenehmen Geruch verströmend", "mis kokulu", "", ""),
    "durchdacht": ("", "sorgfältig und vollständig überlegt", "iyi düşünülmüş", "", ""),
    "durchscheinend": ("", "Licht teilweise hindurchlassend", "yarı saydam", "", ""),
    "eingearbeitet": ("", "in eine Aufgabe eingeübt, auch fest eingefügt", "alıştırılmış, işlenmiş", "", ""),
    "eingebaut": ("", "fest in ein Ganzes integriert", "dahili, gömülü", "", ""),
    "eingebildet": ("", "überheblich, auch nur in der Vorstellung bestehend", "kendini beğenmiş, hayali", "", ""),
    "eingefasst": ("", "mit einem Rand oder Rahmen umgeben", "çerçevelenmiş", "", ""),
    "eingefroren": ("", "tiefgekühlt, auch vorläufig stillgelegt", "donmuş, dondurulmuş", "", ""),
    "eingegangen": ("", "beim Waschen geschrumpft, auch eingetroffen", "çekmiş, gelmiş", "", ""),
    "eingeschlossen": ("", "mit enthalten, auch fest eingesperrt", "dahil, kapatılmış", "", ""),
    "eingewandert": ("", "aus einem anderen Land zugezogen", "göç etmiş", "", ""),
    "eingliedernd": ("", "in ein größeres Ganzes einfügend", "bütünleştirici", "", ""),
    "eingreifend": ("", "aktiv in einen Ablauf hineinwirkend", "müdahaleci", "", ""),
    "einschläfernd": ("", "müde machend und langweilig", "uyutucu, sıkıcı", "", ""),
    "entfernt": ("", "weit weg gelegen, auch beseitigt", "uzak, kaldırılmış", "", ""),
    "entgegengesetzt": ("", "genau umgekehrt, konträr", "zıt, karşıt", "", ""),
    "entgegenkommend": ("", "hilfsbereit und freundlich nachgiebig", "yardımsever, anlayışlı", "", ""),
    "enthemmt": ("", "ohne Scheu und Selbstkontrolle", "çekinmesiz, ölçüsüz", "", ""),
    "entkräftet": ("", "ohne Kraft und völlig erschöpft", "bitkin, halsiz", "", ""),
    "entschieden": ("", "klar und ohne Zögern, fest bestimmt", "kararlı, kesin", "", ""),
    "entsprechend": ("", "dazu passend, einer Sache gemäß", "uygun, ona göre", "", ""),
    "enttäuscht": ("", "in seinen Erwartungen bitter getäuscht", "hayal kırıklığına uğramış", "", ""),
    "entzündet": ("", "gerötet und schmerzhaft gereizt", "iltihaplı", "", ""),
    "erfunden": ("", "frei erdacht und nicht wahr", "uydurma", "", ""),
    "ergänzend": ("", "etwas Fehlendes hinzufügend", "tamamlayıcı", "", ""),
    "erzählend": ("", "eine Geschichte wiedergebend", "anlatısal", "", ""),
    "exaltiert": ("", "übertrieben überschwänglich im Auftreten", "aşırı coşkulu, taşkın", "", ""),
    "vorgeschoben": ("", "nur als Vorwand genannt", "bahane olarak öne sürülen", "", ""),
    "faszinierend": ("", "große Neugier und Bewunderung weckend", "büyüleyici", "", ""),
    "festgelegt": ("", "verbindlich bestimmt und unveränderlich", "belirlenmiş, sabit", "", ""),
    "forciert": ("", "mit Nachdruck erzwungen und dadurch unnatürlich", "zorlama", "", ""),
    "fortschreitend": ("", "sich stetig weiterentwickelnd", "ilerleyen", "", ""),
    "gebildet": ("", "mit umfassendem Wissen ausgestattet", "kültürlü, eğitimli", "", ""),
    "gebraten": ("", "in Fett in der Pfanne gegart", "kızartılmış", "", ""),
    "gedeckt": ("", "gedämpft im Farbton, auch finanziell abgesichert", "mat, teminatlı", "", ""),
    "gedrungen": ("", "klein und kräftig gebaut", "tıknaz", "", ""),
    "gedämpft": ("", "leise und in der Wirkung abgeschwächt", "kısık, hafifletilmiş", "", ""),
    "gefangen": ("", "der Freiheit beraubt", "tutsak, yakalanmış", "", ""),
    "gefragt": ("", "stark nachgefragt und beliebt", "rağbet gören", "", ""),
    "gefüllt": ("", "mit etwas angefüllt", "dolu, doldurulmuş", "", ""),
    "gehasst": ("", "von vielen heftig abgelehnt", "nefret edilen", "", ""),
    "geheiligt": ("", "als heilig verehrt", "kutsanmış", "", ""),
    "gekürzt": ("", "im Umfang verringert", "kısaltılmış", "", ""),
    "gelehrt": ("", "von großer Gelehrsamkeit zeugend", "bilgin, âlim", "", ""),
    "gemischt": ("", "aus Verschiedenartigem zusammengesetzt", "karışık", "", ""),
    "gemäßigt": ("", "maßvoll und ohne Extreme", "ılımlı", "", ""),
    "genervt": ("", "gereizt und ungeduldig", "bunalmış, sinirli", "", ""),
    "genormt": ("", "nach einer festen Norm vereinheitlicht", "standartlaştırılmış", "", ""),
    "geordnet": ("", "in klarer und übersichtlicher Ordnung", "düzenli", "", ""),
    "gepfeffert": ("", "scharf gewürzt, auch überteuert", "biberli, tuzlu", "", ""),
    "geplant": ("", "im Voraus vorgesehen", "planlanmış", "", ""),
    "geprüft": ("", "auf Richtigkeit kontrolliert und bestätigt", "denetlenmiş, onaylı", "", ""),
    "geputzt": ("", "gründlich sauber gemacht", "temizlenmiş", "", ""),
    "geriffelt": ("", "mit feinen parallelen Rillen versehen", "yivli, oluklu", "", ""),
    "gerissen": ("", "schlau und durchtrieben", "kurnaz", "", ""),
    "gerüstet": ("", "auf etwas gut vorbereitet", "hazırlıklı", "", ""),
    "geschickt": ("", "mit Geschick und Gewandtheit ausgeführt", "becerikli, hünerli", "", ""),
    "geschröpft": ("", "finanziell stark ausgenommen", "soyulmuş", "", ""),
    "geschützt": ("", "vor Gefahr und Zugriff bewahrt", "korunmuş", "", ""),
    "gestresst": ("", "unter starkem Druck und Anspannung stehend", "stresli", "", ""),
    "gestrichelt": ("", "aus kurzen Strichen bestehend", "kesik çizgili", "", ""),
    "gestört": ("", "in seinem Ablauf spürbar beeinträchtigt", "bozulmuş, aksamış", "", ""),
    "gesättigt": ("", "vollständig satt oder aufnahmefähig ausgefüllt", "doymuş", "", ""),
    "getakelt": ("", "mit Masten, Segeln und Tauwerk ausgerüstet", "donanımlı", "", ""),
    "getrieben": ("", "innerlich rastlos angetrieben", "dürtülen, huzursuz", "", ""),
    "gewagt": ("", "kühn und mit Risiko verbunden", "cüretkâr, riskli", "", ""),
    "gewandt": ("", "geschickt und sicher im Auftreten", "becerikli, kıvrak", "", ""),
    "gewunden": ("", "in vielen Kurven verlaufend, auch umständlich", "kıvrımlı, dolambaçlı", "", ""),
    "gezackt": ("", "mit spitzen Zacken versehen", "tırtıklı, dişli", "", ""),
    "gezeichnet": ("", "von Leid und Krankheit sichtbar geprägt", "yıpranmış, iz taşıyan", "", ""),
    "gezielt": ("", "genau auf ein bestimmtes Ziel gerichtet", "hedefe yönelik", "", ""),
    "gezähmt": ("", "zahm und zutraulich gemacht", "evcilleştirilmiş", "", ""),
    "grundlegend": ("", "die Grundlage bildend und daher wesentlich", "temel, esaslı", "", ""),
    "hemmend": ("", "den Fortgang bremsend", "engelleyici, ket vurucu", "", ""),
    "herabgesetzt": ("", "im Preis gesenkt, auch in seinem Wert gemindert", "indirimli, küçümsenmiş", "", ""),
    "herausfordernd": ("", "zum Widerspruch oder Wettstreit reizend", "meydan okuyan", "", ""),
    "herausgegeben": ("", "als Herausgeber veröffentlicht", "yayımlanmış", "", ""),
    "heruntergekommen": ("", "in einen schlechten und verwahrlosten Zustand geraten", "bakımsız, harap", "", ""),
    "hingewiesen": ("", "ausdrücklich auf etwas aufmerksam gemacht", "işaret edilmiş", "", ""),
    "interessiert": ("", "Anteilnahme und Neugier zeigend", "ilgili, meraklı", "", ""),
    "lebend": ("", "am Leben befindlich", "yaşayan, canlı", "", ""),
    "leitend": ("", "eine Führungsaufgabe innehabend", "yönetici", "", ""),
    "missfallend": ("", "Widerwillen und Ablehnung hervorrufend", "hoşa gitmeyen", "", ""),
    "nachwachsend": ("", "sich von selbst wieder erneuernd", "yenilenebilir", "", ""),
    "passend": ("", "genau geeignet und dazu stimmend", "uygun, yakışan", "", ""),
    "preisgegeben": ("", "schutzlos überlassen und aufgegeben", "terk edilmiş, feda edilmiş", "", ""),
    "prädestiniert": ("", "für eine Aufgabe wie geschaffen", "biçilmiş kaftan", "", ""),
    "quälend": ("", "starke Schmerzen oder Not bereitend", "eziyet verici", "", ""),
    "retardiert": ("", "verlangsamt und in der Entwicklung verzögert", "gecikmeli, yavaşlatılmış", "", ""),
    "schwankend": ("", "hin und her pendelnd, unbeständig", "dalgalı, kararsız", "", ""),
    "verblüht": ("", "nicht mehr in Blüte, welk geworden", "solmuş", "", ""),
    "verfrüht": ("", "zu früh und damit unpassend erfolgt", "erken, vakitsiz", "", ""),
    "verletzt": ("", "körperlich oder seelisch versehrt", "yaralı, incinmiş", "", ""),
    "verwandt": ("", "durch Abstammung oder Wesensart verbunden", "akraba, ilişkili", "", ""),
    "vorangegangen": ("", "zeitlich unmittelbar davor liegend", "önceki", "", ""),
    "wiedergewinnend": ("", "Verlorenes zurückholend", "geri kazandıran", "", ""),
    "ätzend": ("", "chemisch aggressiv, auch scharf spöttisch", "yakıcı, iğneleyici", "", ""),
    "überdimensioniert": ("", "viel zu groß bemessen", "aşırı büyük", "", ""),
    "überschäumend": ("", "vor Begeisterung übersprudelnd", "coşkun, taşkın", "", ""),
}
