#!/usr/bin/env python3
"""Fix low-quality, self-referential placeholder EXAMPLE sentences across
data/*.js (English, German -- French has none of this issue, verified).

Three known placeholder wordings (all mechanically generated by earlier
bulk-import/enrichment scripts in this project, never real usage examples):
    EN: 'I am learning the word "X". - "X" kelimesini öğreniyorum.'
    DE: 'Ich lerne das Wort/Verb "X". - "X" kelimesini öğreniyorum.'
    EN (synant): '"X" is a useful word to know.;"Y" bilinmesi yararlı bir kelimedir.'
These sentences are contentless (any word fits grammatically -- they teach
nothing about the word's actual usage), reported as "useless" by the user.

Strategy: source a REAL example sentence for each affected word from the
Tatoeba open sentence corpus (CC BY 2.0 FR, bulk per-language TSV export --
https://tatoeba.org/en/downloads), which is:
  - Free, no API key, no per-request rate limit (one-time bulk download,
    then pure local text matching -- avoids the dictionaryapi.dev/Wiktionary
    per-word rate-limit walls hit repeatedly in earlier sessions).
  - Real, natural, contributor-written sentences -- appropriate for a
    language-learning app (this is literally Tatoeba's purpose).
Falls back to a fuzzy (inflection-tolerant) match for words not found
verbatim (same common-prefix heuristic as shared.js's czFindSpan()), and to
an HONEST "no example sentence available" fallback (never a fabricated
sentence) for words with no corpus hit at all -- matches this project's
established fallback precedent for un-sourceable dictionary content.

Chosen sentences are machine-translated to Turkish (Google Translate free
endpoint, same proven threaded+rate-limited pattern as
translate_and_build_synant.py) to fill the established "native - Turkish"
(or "native;Turkish" for the *synant*.js files) format.

Phases (run in order; each is resumable via its own on-disk cache):
    scan       - find all placeholder entries in every target file, report counts.
    index      - download Tatoeba corpora, match each unique affected word to
                 a real sentence (or None), cache to WORD_MATCH_CACHE.
    translate  - translate every matched sentence to Turkish, cache to
                 TRANSLATE_CACHE.
    apply      - rewrite each data file, replacing every placeholder example.
    all        - run all four in sequence.

Usage: python scripts/fix_placeholder_examples.py [--phase all] [--lang both] [--limit N]
"""
import os
import re
import sys
import bz2
import json
import math
import time
import argparse
import threading
import urllib.request
import urllib.parse
import urllib.error
from concurrent.futures import ThreadPoolExecutor, as_completed

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
TEMP = os.environ.get("TEMP", ".")

TATOEBA_URLS = {
    "de": "https://downloads.tatoeba.org/exports/per_language/deu/deu_sentences.tsv.bz2",
    "en": "https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences.tsv.bz2",
    "fr": "https://downloads.tatoeba.org/exports/per_language/fra/fra_sentences.tsv.bz2",
}
TATOEBA_BZ2 = {
    "de": os.path.join(TEMP, "deu_sentences.tsv.bz2"),
    "en": os.path.join(TEMP, "eng_sentences.tsv.bz2"),
    "fr": os.path.join(TEMP, "fra_sentences.tsv.bz2"),
}
WORD_MATCH_CACHE = os.path.join(TEMP, "example_fix_word_matches.json")
TRANSLATE_CACHE = os.path.join(TEMP, "example_fix_translate_cache.json")

HEADERS = {
    "User-Agent": "TopWordsApp/1.0 (free educational Turkish vocabulary app; "
    "https://udsp.vercel.app)"
}

# (path, lang, separator-in-final-example-string)
FILES = [
    (os.path.join(DATA, "wordsa1.js"), "en", " - "),
    (os.path.join(DATA, "wordsa2.js"), "en", " - "),
    (os.path.join(DATA, "wordsb1.js"), "en", " - "),
    (os.path.join(DATA, "wordsb2.js"), "en", " - "),
    (os.path.join(DATA, "wordsc1.js"), "en", " - "),
    (os.path.join(DATA, "wordsc2.js"), "en", " - "),
    (os.path.join(DATA, "toefl.js"), "en", " - "),
    (os.path.join(DATA, "phrasalverbsen.js"), "en", " - "),
    (os.path.join(DATA, "synanten.js"), "en", ";"),
    (os.path.join(DATA, "wordsa1gode.js"), "de", " - "),
    (os.path.join(DATA, "wordsa2gode.js"), "de", " - "),
    (os.path.join(DATA, "wordsb1gode.js"), "de", " - "),
    (os.path.join(DATA, "wordsb2gode.js"), "de", " - "),
    (os.path.join(DATA, "wordsc1gode.js"), "de", " - "),
    (os.path.join(DATA, "wordsc2gode.js"), "de", " - "),
    (os.path.join(DATA, "partikelverbde.js"), "de", " - "),
    (os.path.join(DATA, "synantde.js"), "de", ";"),
    (os.path.join(DATA, "wordsa1fr.js"), "fr", " - "),
    (os.path.join(DATA, "wordsa2fr.js"), "fr", " - "),
    (os.path.join(DATA, "wordsb1fr.js"), "fr", " - "),
    (os.path.join(DATA, "wordsb2fr.js"), "fr", " - "),
    (os.path.join(DATA, "wordsc1fr.js"), "fr", " - "),
    (os.path.join(DATA, "wordsc2fr.js"), "fr", " - "),
    (os.path.join(DATA, "synantfr.js"), "fr", ";"),
]

WORD_RE = re.compile(r'word:\s*"((?:\\.|[^"])*)"')
EX_RE = re.compile(r'example:\s*"((?:\\.|[^"])*)"')
TOKEN_RE = re.compile(r"[^\W\d_]+", re.UNICODE)
DASHDASH_RE = re.compile(r"\s-\s")
SEMI_RE = re.compile(r";")

PLACEHOLDER_RES = [
    re.compile(r'^I am learning the word\b'),
    re.compile(r'^Ich lerne das (?:Wort|Verb)\b'),
    re.compile(r'is a useful word to know\b'),
    re.compile(r"^J['\u2019]apprends le mot\b"),
    # current honest-fallback wordings -- re-targeted so words that gained a
    # Tatoeba match since the last pass (or via the new FR/DE article-strip)
    # get a real sentence; still-unmatched ones just keep the same fallback.
    re.compile(r'^No example sentence available\b'),
    re.compile(r'^Kein Beispielsatz\b'),
    re.compile(r"^Aucune phrase d'exemple\b"),
]

NOTFOUND_TEXT = {
    "en": "No example sentence available for this word.",
    "de": "Kein Beispielsatz für dieses Wort verfügbar.",
    "fr": "Aucune phrase d'exemple disponible pour ce mot.",
}
NOTFOUND_TR = "Bu kelime için örnek cümle bulunamadı."


def js_unescape(s):
    return s.replace('\\"', '"').replace("\\\\", "\\")


def js_escape(s):
    # NOTE: strip newlines/tabs -- a single raw \n written into a data/*.js
    # string literal breaks the WHOLE site (SyntaxError -> WORDS undefined).
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", " ")
        .replace("\r", " ")
        .replace("\t", " ")
    )


def is_placeholder(example_unescaped):
    return any(p.search(example_unescaped) for p in PLACEHOLDER_RES)


def sanitize_piece(s, sep):
    """Remove the separator character/sequence from fetched/translated text
    before wrapping it in our own '<native><sep><Turkish>' format (same
    rationale as translate_and_build_synant.py's sanitize_piece)."""
    s = (s or "").strip()
    if sep == " - ":
        s = DASHDASH_RE.sub(", ", s)
    else:
        s = SEMI_RE.sub(",", s)
    return s


def ensure_period(s):
    s = (s or "").strip()
    if s and s[-1] not in ".!?":
        s += "."
    return s


def load_json(path):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_json(path, data):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False)
    os.replace(tmp, path)


def scan_file(path):
    text = open(path, encoding="utf-8").read()
    words = list(WORD_RE.finditer(text))
    exs = list(EX_RE.finditer(text))
    if len(words) != len(exs):
        raise RuntimeError(f"{path}: word/example count mismatch {len(words)} vs {len(exs)}")
    entries = []
    for wm, em in zip(words, exs):
        word = js_unescape(wm.group(1))
        ex = js_unescape(em.group(1))
        entries.append({"word": word, "ex_match": em, "placeholder": is_placeholder(ex)})
    return text, entries


def phase_scan(limit=None):
    total = 0
    target_words = {"en": set(), "de": set(), "fr": set()}
    per_file = {}
    for path, lang, sep in FILES:
        text, entries = scan_file(path)
        ph = [e for e in entries if e["placeholder"]]
        per_file[os.path.basename(path)] = len(ph)
        total += len(ph)
        for e in ph:
            target_words[lang].add(e["word"])
    for name, count in per_file.items():
        print(f"[scan] {name}: {count} placeholder examples", flush=True)
    print(f"[scan] TOTAL placeholder examples = {total}", flush=True)
    print(f"[scan] unique EN words = {len(target_words['en'])}", flush=True)
    print(f"[scan] unique DE words = {len(target_words['de'])}", flush=True)
    print(f"[scan] unique FR words = {len(target_words['fr'])}", flush=True)
    return target_words


# ---------------------------------------------------------------------------
# Tatoeba corpus download + matching
# ---------------------------------------------------------------------------

def ensure_tatoeba(lang):
    path = TATOEBA_BZ2[lang]
    if os.path.exists(path) and os.path.getsize(path) > 1_000_000:
        return path
    url = TATOEBA_URLS[lang]
    print(f"[tatoeba] downloading {url}", flush=True)
    req = urllib.request.Request(url, headers=HEADERS)
    tmp = path + ".tmp"
    with urllib.request.urlopen(req, timeout=120) as resp, open(tmp, "wb") as f:
        while True:
            chunk = resp.read(1024 * 256)
            if not chunk:
                break
            f.write(chunk)
    os.replace(tmp, path)
    print(f"[tatoeba] downloaded {os.path.getsize(path)} bytes -> {path}", flush=True)
    return path


def load_sentences(lang):
    path = ensure_tatoeba(lang)
    sentences = []
    with bz2.open(path, "rt", encoding="utf-8", errors="replace") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 3:
                continue
            text = parts[2].strip()
            if text:
                sentences.append(text)
    print(f"[tatoeba] {lang}: {len(sentences)} sentences loaded", flush=True)
    return sentences


def fuzzy_ok(token_lower, target_lower):
    if len(target_lower) < 5:
        return False
    common = 0
    for a, b in zip(token_lower, target_lower):
        if a == b:
            common += 1
        else:
            break
    needed = max(5, math.ceil(0.65 * len(target_lower)))
    return common >= needed and abs(len(token_lower) - len(target_lower)) <= 5


def is_good_candidate(sentence):
    n = len(sentence)
    if n < 8 or n > 180:
        return False
    words = sentence.split()
    return 2 <= len(words) <= 25


_ART_FR = re.compile(r"^(?:le|la|les|un|une)\s+|^l['\u2019]", re.IGNORECASE)
_ART_DE = re.compile(r"^(?:der|die|das)\s+", re.IGNORECASE)


def search_form(word, lang):
    """Article-stripped single-token form to look up in the corpus. French and
    German nouns store their article in `word` ("le mot", "die Katze") -- without
    stripping it the word looks multi-token and gets skipped, so article-bearing
    nouns never matched before. Keyed back to the ORIGINAL word by the caller."""
    w = (word or "").strip()
    if lang == "fr":
        w = _ART_FR.sub("", w).strip()
    elif lang == "de":
        w = _ART_DE.sub("", w).strip()
    return w


def match_words_to_sentences(words, sentences, lang):
    """Returns {original_word: sentence_or_None}. Looks each word up by its
    article-stripped single-token search form; words whose search form is still
    multi-token (phrases) are skipped (same single-token scoping as Cloze Test)."""
    sf_to_orig = {}   # search_form_lower -> [original words]
    multi = []
    for w in words:
        sf = search_form(w, lang)
        if not sf or " " in sf:
            multi.append(w)
        else:
            sf_to_orig.setdefault(sf.lower(), []).append(w)
    target_lower = set(sf_to_orig.keys())
    best = {}  # sf_lower -> (length, sentence)

    for sent in sentences:
        if not is_good_candidate(sent):
            continue
        for tok in TOKEN_RE.findall(sent):
            tl = tok.lower()
            if tl in target_lower and tl not in best:
                best[tl] = (len(sent), sent)

    leftover = [sf for sf in target_lower if sf not in best]
    if leftover:
        buckets = {}
        for sf in leftover:
            if len(sf) >= 5:
                buckets.setdefault(sf[:5], []).append(sf)
        if buckets:
            for sent in sentences:
                if not is_good_candidate(sent):
                    continue
                for tok in TOKEN_RE.findall(sent):
                    tl = tok.lower()
                    if len(tl) < 5:
                        continue
                    cands = buckets.get(tl[:5])
                    if not cands:
                        continue
                    for sf in cands:
                        if sf in best:
                            continue
                        if fuzzy_ok(tl, sf):
                            best[sf] = (len(sent), sent)

    result = {}
    for sf, origs in sf_to_orig.items():
        hit = best.get(sf)
        for o in origs:
            result[o] = hit[1] if hit else None
    for w in multi:
        result[w] = None
    return result


def phase_index(target_words, limit=None):
    cache = load_json(WORD_MATCH_CACHE)
    for lang in ("en", "de", "fr"):
        words = sorted(target_words[lang])
        if limit:
            words = words[:limit]
        # Retry words with no cached match (value falsy/None) too -- the new
        # FR/DE article-stripping search form unlocks article-bearing nouns
        # that were skipped (and cached as None) on earlier passes.
        todo = [w for w in words if not cache.get(w)]
        print(f"[index] {lang}: {len(words)} target words, {len(todo)} need matching", flush=True)
        if not todo:
            continue
        sentences = load_sentences(lang)
        matches = match_words_to_sentences(todo, sentences, lang)
        del sentences
        hit = sum(1 for v in matches.values() if v)
        print(f"[index] {lang}: matched {hit}/{len(todo)} words to a real sentence", flush=True)
        cache.update(matches)
        save_json(WORD_MATCH_CACHE, cache)
    return cache


# ---------------------------------------------------------------------------
# Translation (Google Translate free endpoint -- proven pattern reused
# from translate_and_build_synant.py / fix_placeholder_definitions.py)
# ---------------------------------------------------------------------------

class RateLimiter:
    def __init__(self, min_interval):
        self.min_interval = min_interval
        self.lock = threading.Lock()
        self.next_time = 0.0

    def wait(self):
        with self.lock:
            now = time.time()
            start_at = max(now, self.next_time)
            self.next_time = start_at + self.min_interval
        delay = start_at - now
        if delay > 0:
            time.sleep(delay)


TRANSLATE_LIMITER = RateLimiter(0.15)  # ~6.6 req/s, matches earlier proven-safe rate


class Transient(Exception):
    pass


def translate_one(text, src, tgt, attempts=4, base_delay=0.6):
    q = urllib.parse.quote(text.replace("\n", " ").strip())
    url = (
        "https://translate.googleapis.com/translate_a/single"
        f"?client=gtx&sl={src}&tl={tgt}&dt=t&q={q}"
    )
    last_err = None
    for i in range(attempts):
        TRANSLATE_LIMITER.wait()
        try:
            req = urllib.request.Request(url, headers=HEADERS)
            with urllib.request.urlopen(req, timeout=20) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            return "".join(seg[0] for seg in data[0])
        except Exception as e:
            last_err = e
        time.sleep(base_delay * (2**i))
    raise Transient(str(last_err))


def phase_translate(match_cache):
    translate_cache = load_json(TRANSLATE_CACHE)
    jobs = []
    seen = set()
    for path, lang, sep in FILES:
        _, entries = scan_file(path)
        for e in entries:
            if not e["placeholder"]:
                continue
            sent = match_cache.get(e["word"])
            if not sent:
                continue
            piece = sanitize_piece(sent, sep)
            key = f"{lang}|tr|{piece}"
            if key in translate_cache or key in seen or not piece:
                continue
            seen.add(key)
            jobs.append((lang, "tr", piece, key))
    print(f"[translate] distinct sentences to translate = {len(jobs)}", flush=True)
    if not jobs:
        return translate_cache
    done = skipped = 0
    start = time.time()
    with ThreadPoolExecutor(max_workers=8) as ex:
        futures = {ex.submit(translate_one, text, src, tgt): key for src, tgt, text, key in jobs}
        for fut in as_completed(futures):
            key = futures[fut]
            try:
                translate_cache[key] = fut.result()
            except Transient:
                skipped += 1
            done += 1
            if done % 200 == 0 or done == len(jobs):
                save_json(TRANSLATE_CACHE, translate_cache)
                elapsed = max(0.001, time.time() - start)
                rate = done / elapsed
                remain = (len(jobs) - done) / rate if rate else 0
                print(
                    f"[translate] {done}/{len(jobs)} ({rate:.1f}/s, ~{remain/60:.1f} min left, {skipped} skipped-for-retry)",
                    flush=True,
                )
    save_json(TRANSLATE_CACHE, translate_cache)
    return translate_cache


# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

def apply_replacements(text, entries, new_exs):
    edits = []
    for i, new_text in new_exs.items():
        m = entries[i]["ex_match"]
        edits.append((m.start(1), m.end(1), js_escape(new_text)))
    edits.sort(key=lambda x: x[0], reverse=True)
    for start, end, repl in edits:
        text = text[:start] + repl + text[end:]
    return text


def phase_apply(match_cache, translate_cache):
    total_fixed = 0
    total_fallback = 0
    for path, lang, sep in FILES:
        text, entries = scan_file(path)
        new_exs = {}
        file_fixed = file_fallback = 0
        for i, e in enumerate(entries):
            if not e["placeholder"]:
                continue
            sent = match_cache.get(e["word"])
            tr = ""
            if sent:
                piece = sanitize_piece(sent, sep)
                key = f"{lang}|tr|{piece}"
                tr = translate_cache.get(key, "")
            if sent and tr:
                new_exs[i] = f"{ensure_period(piece)}{sep}{ensure_period(tr)}"
                file_fixed += 1
            else:
                new_exs[i] = f"{NOTFOUND_TEXT[lang]}{sep}{NOTFOUND_TR}"
                file_fallback += 1
        if not new_exs:
            continue
        updated = apply_replacements(text, entries, new_exs)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(updated)
        total_fixed += file_fixed
        total_fallback += file_fallback
        print(f"[apply] {os.path.basename(path)}: fixed={file_fixed} fallback_used={file_fallback}", flush=True)
    print(f"[apply] DONE total_fixed_with_real_sentence={total_fixed} total_honest_fallback={total_fallback}", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", default="all", choices=["scan", "index", "translate", "apply", "all"])
    ap.add_argument("--limit", type=int, default=None, help="Only process first N unique words per language (smoke test)")
    args = ap.parse_args()

    if args.phase in ("scan", "all"):
        target_words = phase_scan(args.limit)
    if args.phase == "scan":
        return

    if args.phase in ("index", "all"):
        if args.phase == "index":
            target_words = phase_scan(args.limit)
        match_cache = phase_index(target_words, args.limit)
    if args.phase == "index":
        return

    if args.phase in ("translate", "all"):
        if args.phase == "translate":
            match_cache = load_json(WORD_MATCH_CACHE)
        translate_cache = phase_translate(match_cache)
    if args.phase == "translate":
        return

    if args.phase in ("apply", "all"):
        if args.phase == "apply":
            match_cache = load_json(WORD_MATCH_CACHE)
            translate_cache = load_json(TRANSLATE_CACHE)
        phase_apply(match_cache, translate_cache)


if __name__ == "__main__":
    main()
